import {migrateApplicationConversations} from './migrations.mjs';
const states=[['found','Bulundu'],['working','İşleniyor'],['prepared','Hazırlandı'],['submitting','Gönderiliyor'],['submitted','Başvuruldu'],['already_submitted','Önceden başvuruldu'],['uncertain','Doğrulama bekliyor'],['blocked','Yanıt bekliyor'],['skipped','Atlandı'],['withdrawn','Geri çekildi']];
export const jobSearchDefinition={id:'applications',legacyWorkspaces:[{table:'candidates',defaultTemplate:'job-search'}],legacyRecords:[{table:'jobs',owner:'candidate_id',key:'url',identity:'identity'}],legacyWorkers:[{table:'agent_workers',owner:'candidate_id'}],migrate:migrateApplicationConversations,kind:'jobs',capabilities:{'jobs.search':{effect:'read'},'jobs.rank':{effect:'read'},'jobs.prepare':{effect:'prepare'},'jobs.apply':{effect:'write'},'jobs.verify':{effect:'read'}},browserModes:['existing','separate','jev'],defaultBrowserMode:'existing',workflow:[
  {id:'search',capability:'jobs.search',scope:'source',instructions:'İlanları bul.'},
  {id:'rank',capability:'jobs.rank',scope:'record',instructions:'Uygunluğu puanla.',after:['search']},
  {id:'preparation',capability:'jobs.prepare',scope:'record',instructions:'Başvuru paketini hazırla.',after:['rank']},
  {id:'application',capability:'jobs.apply',scope:'record',instructions:'Yetki kapsamında başvur.',after:['rank']},
  {id:'verify',capability:'jobs.verify',scope:'record',instructions:'Gönderim sonucunu doğrula.',after:['application']}
 ],records:{states:states.map(([id,label])=>({id,label})),bindings:{source:'company',title:'role',location:'location'}},templates:[{id:'job-search',version:1,title:'İş arama',icon:'↗',description:'Uygun ilanları bul, değerlendir, başvur ve yanıtları takip et.',kind:'jobs',table:{title:'Başvuru akışı',columns:[{key:'source',label:'Şirket',type:'text'},{key:'title',label:'Pozisyon',type:'text'},{key:'location',label:'Konum',type:'text'}]},fields:[],steps:['Profili oluştur','İlanları bul ve değerlendir','Başvuruları hazırla veya gönder','Yanıtları takip et']}],projectRecord:record=>({documents:record.documents??record.preparation?.documents??[],evidence:record.proof??record.evidence??null}),validateTable(table){if(table.columns.some(c=>c.key==='rank'))throw Error('Puan sütunu iş arama template’i tarafından yönetilir');}};
