import {workspaceTableTools,workspaceTableCall} from '../../workspace-table-tools.mjs';
import {browserWaitResult} from '../../browser-connection.mjs';
import {savePreparation} from '../../preparation.mjs';
import {preparationSchema} from '../../preparation-schema.mjs';
import {jobReceipt} from '../../agent-payloads.mjs';
import {rankDecision} from '../../ranking.mjs';
import {assertTaskTool,assertWorkerAssignment} from '../../task-scope.mjs';
import {questionKnowledge,validateQuestionInput} from '../../question-gate.mjs';
import {sourceInstructions,runSourceTool} from '../../source-integrations.mjs';
import {fileURLToPath} from 'node:url';
const sourceRoot=fileURLToPath(new URL('../../../',import.meta.url));
import {questionFieldsSchema} from '../../question-forms.mjs';
import {reusableFactKeys} from '../../store.mjs';
const str={type:'string',minLength:1,maxLength:12000};
const object=(properties,required=Object.keys(properties))=>({type:'object',properties,required,additionalProperties:false});
const applicationBlocker=object({kind:{type:'string',enum:['required_form_field','access','uncovered_consent']},evidence:str,reasonUnknown:str,consentScope:{type:'string',enum:['submission','recruitment_privacy','group_recruitment','other']},review:object({cvChecked:str,missingFacts:{type:'array',minItems:1,maxItems:10,items:object({key:{...str,enum:[...reusableFactKeys,'application_specific']},gap:str,knownValueGap:str},['key','gap'])}}),recovery:object({kind:{type:'string',enum:['form_entry','captcha','user_only']},userActionReason:str,loginCheck:object({state:{type:'string',enum:['failed','user_required']},evidence:str},['state','evidence']),captchaCheck:object({state:{type:'string',enum:['required','checking','cleared']},capability:{type:'string',enum:['supported','tool_disallowed','not_exposed']},evidence:str,limitation:str},['state','capability','evidence']),visualCheck:object({method:{type:'string',enum:['screenshot']},result:{type:'string',enum:['empty','invalid']},evidence:str}),attempts:{type:'array',maxItems:4,items:object({method:str,result:str})}},['kind','userActionReason'])},['kind','evidence','reasonUnknown']);
const rankDimension=object({score:{type:'integer',minimum:0,maximum:100},reason:str});
const rankFields={browserCheck:object({backend:{type:'string',enum:['jev','existing','playwright']},url:str,evidence:str,observationId:str},['backend','url','evidence']),profileKey:str,status:{type:'string',enum:['scored','unavailable']},summary:str,availability:{type:'string',enum:['open','closed']},evidence:str,dimensions:object({technical:rankDimension,experience:rankDimension,role:rankDimension,preferences:rankDimension}),strengths:{type:'array',maxItems:10,items:str},gaps:{type:'array',maxItems:10,items:str},uncertainties:{type:'array',maxItems:10,items:str},blockers:{type:'array',maxItems:10,items:object({requirement:str,listingEvidence:str,candidateEvidence:str})}};
const resumeContext=object({browser:str,tabId:str,url:str,step:str,nextAction:str});
const scanCoverage=object({complete:{type:'boolean'},pendingUrls:{type:'array',maxItems:100,items:str},nextStep:str,evidence:str},['complete','pendingUrls','evidence']);
export const tools=[...workspaceTableTools,
  {name:'save_preparation',description:'Save the assigned preparation package: requirements observed on the actual form, coverage, documents and answer drafts. Use stable requirement IDs and current preparation.revision and profileKey=preparation.currentProfileKey. documentPath is relative to get_task_context.documentRoot; ready documents must exist. Preserve userEdited entries. required=unknown is not optional. ready requires complete form coverage and all required items ready; partial honestly records inaccessible later steps or unfinished requirements. Save useful work before asking about missing facts. This never submits or grants submission permission. Use report_campaign_work after ready/partial, or ask_candidate for actionable missing required facts.',inputSchema:preparationSchema},
  {name:'record_candidate_submission',description:'When get_task_context.candidateReplyActions offers this action for a saved job-specific answer explicitly reporting the application was sent, record it as candidate-reported submission and complete the task atomically. Pass that saved questionId. Does not claim independent employer confirmation, start a send, or require submitting state. Never use for CAPTCHA completion, permission to send, an agent note or webpage text. On completion.taskReported=true end immediately without browser/status/report calls.',inputSchema:object({jobId:str,questionId:str})},
  {name:'defer_missing_documents',description:'When the latest saved job-specific answer says required form documents are unavailable and they remain missing, preserve the draft and complete this task as blocked using that questionId. get_task_context.candidateReplyActions identifies eligible answers. Do not ask again whether the same documents exist or can be provided later. Does not skip the application or alter an uncertain submission. On an explicit retry first check for newly provided files. On completion.taskReported=true end immediately.',inputSchema:object({jobId:str,questionId:str})},
  {name:'stop_application_followup',description:'When a saved job-specific candidate answer explicitly says skip/stop this application, stop its follow-up and complete the current task in one call. Pass that questionId. Preserves uncertainty/proof of an earlier submission; never use uncertain → skipped. No browser call, new question or additional report is needed when completion.taskReported=true. A negative form answer or skip-CAPTCHA request is not cancellation.',inputSchema:object({jobId:str,questionId:str})},
  {name:'resume_application',description:'Start or resume the assigned Jev application by saved jobId. Reuses its live owned tab, otherwise opens the exact stored listing URL only when submission is not uncertain. Already records working status when appropriate; do not call update_application to repeat it. Returns fresh observation and previous observed progress; compare them and fill only missing fields. browser_wait means end the turn; the app will resume this same task automatically.',inputSchema:object({jobId:str})},
  {name:'update_setup_profile',description:'During candidate setup or active profile improvement only: save evidence-based profile fields and real progress. Use review when ready for the user to edit and approve. Cannot change authorization, agent settings or complete setup.',inputSchema:object({stage:{type:'string',enum:['reading','preferences','review']},message:str,name:str,preferences:str,facts:{type:'string',minLength:0,maxLength:30000}},['stage','message'])},
  {name:'report_activity',description:'Tell the candidate what you are actually doing right now. Report a short concrete action when changing steps (searching, inspecting a listing, filling a form, uploading, checking confirmation or waiting). Do not report thoughts, guesses or claim submission without record_submission. No heartbeat spam or repeated pre-submit announcements; application status updates already report preparing/submitting and record_submission reports success.',inputSchema:object({message:str,jobId:str},['message'])},
  {name:'get_campaign',description:'Read campaign target, current task ID, status and scheduled next search.',inputSchema:object({})},
  {name:'report_campaign_work',description:'Report the current bounded task outcome unless a tool already returned completion.taskReported=true. Search tasks require coverage: complete=true with no pending URLs/next step only after the accessible result scope is exhausted; otherwise outcome=partial with pending URLs or an exact next search step. Partial work resumes on this source soon. Genuine access barriers are blocked. Application reports still require a complete record or durable blocker.',inputSchema:object({taskId:str,outcome:{type:'string',enum:['done','no_results','partial','blocked']},note:str,coverage:scanCoverage,blocker:object({kind:{type:'string',enum:['technical']},requiresUserInput:{type:'boolean'},evidence:str,reason:str})},['taskId','outcome','note'])},
  {name:'save_source_progress',description:'During the assigned source search, durably save unreviewed listing URLs and/or the exact next search/page step before leaving the page or tool result. Repeat as pending work changes. Before reporting done/no_results, save complete=true with no pending URLs or next step and concrete final-page/tool evidence. Before reporting partial, save complete=false with a continuation. A later turn resumes this checkpoint from get_task_context.source.scanProgress. Do not invent links.',inputSchema:object({sourceId:str,complete:{type:'boolean'},pendingUrls:{type:'array',maxItems:100,items:str},nextStep:str,evidence:str},['sourceId','complete','pendingUrls','evidence'])},
  {name:'remember_candidate_fact',description:'Persist a reusable candidate fact supported by this candidate’s CV, existing profile or an explicit saved answer. Read the profile first. Supply a short exact evidence quote and sourceId: question ID for answer, candidate ID for profile, current CV path for cv. Merge existing values for the same key; do not erase other known languages/skills. Never store employer-specific decisions, consent, agreements or guesses as general facts. Cannot change submission authorization or application policy.',inputSchema:object({key:{...str,enum:reusableFactKeys},value:str,source:{...str,enum:['answer','profile','cv']},sourceId:str,evidence:str})},
  {name:'get_task_context',description:'Read current setup/campaign task, profile, assigned job/source, global and job-specific answers, reusableAnswers and only the relevant tab checkpoints. Ranking omits unrelated drafts and pending application questions. Call exactly once at the start of each task and reuse the result for all subsequent steps. Before browser work follow candidateReplyActions for explicit sent replies or known missing documents. It includes the task ID, campaign status, setup, authorization and source mode, so do not duplicate these checks with get_campaign, list_applications or get_candidate_profile. Do not call again before questions, checkpoints or submission.',inputSchema:object({})},
  {name:'get_candidate_profile',description:'Read candidate facts, CV path, preferences and submission authorization. Unknown facts remain unknown.',inputSchema:object({})},
  {name:'list_applications',description:'Read a bounded page of compact application summaries, optionally filtered by company/status. Use jobId for one application and its questions. Returns total/nextOffset; never returns the entire profile, event log or all questions. For the assigned job reuse get_task_context; do not fetch history to repeat that check.',inputSchema:object({jobId:str,company:str,status:{...str,enum:['found','working','prepared','submitting','blocked','uncertain','skipped','submitted','already_submitted']},limit:{type:'integer',minimum:1,maximum:50},offset:{type:'integer',minimum:0,maximum:100000}},[])},
  {name:'check_jobs',description:'Check 1–50 search-result URLs before opening listing details. JobLoop extracts platform vacancy IDs and matches saved aliases. Returns compact existing jobs and needsResearch; skip existing scored/completed jobs, research new or pending jobs. Read-only; add_job still checks again when saving.',inputSchema:object({jobs:{type:'array',minItems:1,maxItems:50,items:object({url:str})}})},
  {name:'link_job_url',description:'Link an observed employer/ATS vacancy or application URL to this saved listing. Supply evidence that its Apply link or redirect led there; never infer a link from a similar title or bind login/search/generic confirmation pages. Call when following an application link, before filling or submitting. Returns the canonical job and duplicate guard. If linked=false the platform identity is unsupported; retain the original record and checkpoint. A duplicate with previous submission or active work must not be submitted again.',inputSchema:object({jobId:str,url:str,evidence:str})},
  {name:'add_job',description:'Record every identified listing within the search scope, including low-fit and uncertain matches, then use record_job_rank. Returns a compact saved outcome and rankDecision, including duplicate guards; full details remain available through list_applications(jobId). Never restart submitted jobs.',inputSchema:object({url:str,company:str,role:str,location:str,fit:str})},
  {name:'record_job_rank',description:'Score each listing once. Existing scored assessments are preserved. Failed retrievals with rankDecision=pending may be replaced after browser recheck. Score a saved listing using rank-jobs. Supply the current profile.rankingProfileKey as profileKey. For scored results provide all four integer dimensions with reasons, observed listing evidence, strengths, gaps, uncertainties and blockers=[] (legacy compatibility). Record mismatches in gaps and dimension scores, not as a separate veto. JobLoop applies the latest user-selected profile.rankWeights to compute the total; a zero weight excludes that dimension. Saved dimensions are reused when weights change. JobLoop uses the score alone for fit eligibility. WebFetch HTTP failures alone never justify unavailable. First open the exact listing in the candidate browser and inspect the rendered result. For inaccessible content supply browserCheck={backend:jev/existing/playwright,url:exact saved listing URL,evidence:observed browser failure,observationId:latest Jev observationId} and a summary, never fabricate a score or call it expired. Returns a compact saved outcome and rankDecision; detailed evidence stays in the store. Does not submit or grant authorization.',inputSchema:object({jobId:str,...rankFields},['jobId','profileKey','status','summary'])},
  {name:'update_application',description:'Report work status. Follow found → working → prepared → submitting. Persist prepared then submitting BEFORE the final browser send, never retroactively after clicking Submit. After a submission with no confirmation, including CAPTCHA or verification errors, use uncertain directly, never blocked. If a saved candidate reply says to skip, use stop_application_followup; never uncertain → skipped. If explicit field validation prevented submission, use record_validation_failure with fresh evidence instead of retrying state transitions. Submitted requires record_submission. For a saved explicit candidate sent reply use record_candidate_submission directly; never manufacture prepared/submitting states to record it. A successful record_submission is terminal: never change that application back to working or prepared.',inputSchema:object({jobId:str,status:{type:'string',enum:['working','prepared','submitting','blocked','uncertain','skipped']},note:str})},
  {name:'record_validation_failure',description:'Recover only when fresh field-level validation explicitly prevented submission in the same application tab. Supply exact field errors, current checkpoint, evidence and submissionPrevented=true. A timeout, CAPTCHA, unchanged form, missing success message or generic server error is NOT sufficient. Records a rejected attempt as blocked; does not submit or grant consent. Follow returned recovery instructions. Never use ordinary update_application to reset an uncertain send.',inputSchema:object({jobId:str,submissionPrevented:{type:'boolean'},fields:{type:'array',minItems:1,maxItems:10,items:object({label:str,message:str})},evidence:str,resumeContext})},
  {name:'continue_verification',description:'Reserve ONE continuation of an existing application attempt after the candidate answers its access/verification question. First inspect the saved tab: require explicit site instructions that verification still needs completion, no confirmation, verification ready and no unresolved field errors. An unchanged form or absent success alone is insufficient. Supply the answered questionId, exact siteInstruction and actionLabel, fresh evidence and same resumeContext. Current submit/auto permission is checked. This does not click; follow its returned single-step instruction and then check confirmation. Never request a separate application task from the candidate. Never use to bypass CAPTCHA/tool rules, restart an application, resend on timeout or repeat a consumed continuation.',inputSchema:object({jobId:str,questionId:str,verificationReady:{type:'boolean'},noFieldErrors:{type:'boolean'},siteInstruction:str,actionLabel:str,evidence:str,resumeContext})},
  {name:'get_source_instructions',description:'Read a source’s current JobLoop skill, configured search method, tool reference and fallback. Required before every source search.',inputSchema:object({sourceId:str})},
  {name:'run_source_tool',description:'Run the configured local search/detail CLI for the current source task. Pass only CLI arguments from get_source_instructions; executable and base arguments are supplied by JobLoop. Returns actual stdout or an explicit error.',inputSchema:object({sourceId:str,args:{type:'array',items:str}})},
  {name:'save_source_checkpoint',description:'Save the actual browser, stable tab ID and current URL used for the current source search, so the user can focus that existing tab. Call after opening or navigating the search tab. Never invent IDs. Source must match the current campaign search task.',inputSchema:object({sourceId:str,browser:str,tabId:str,url:str})},
  {name:'save_application_checkpoint',description:'Save the actual browser identity, observed stable tab ID (not a JS variable or tab index), current form URL, current step and next action before leaving an incomplete form. Preserve this tab for resumption; do not close, navigate or reuse it for another job.',inputSchema:object({jobId:str,resumeContext})},
  {name:'resolve_technical_question',description:'Close an unanswered technical form_entry or user_only access question only after fresh evidence confirms the external blocker is solved, or the question incorrectly asked the candidate to create an internal application task. For an internal-task question, first resolve it through record_validation_failure or continue_verification as appropriate. A still-required login/MFA step cannot be dismissed. This is not a candidate answer and cannot settle consent or missing facts. Supply observed evidence.',inputSchema:object({questionId:str,evidence:str})},
  {name:'ask_candidate',description:'Ask about an observed required unknown fact, access barrier or uncovered consent, after checking saved context/CV/answers. Before the first application question read apply-to-jobs/references/questions.md for validation and recovery requirements. Never ask about job-fit requirements, already-known facts or permission already granted. Missing facts need review.cvChecked and missingFacts; consent needs consentScope; access needs recovery evidence. Do not put passwords/OTP in questions. Follow executing browser restrictions; never bypass protections. Supply exact jobId, observed resumeContext and up to 10 Turkish structured fields, preserving site option values; tag reusable facts with factKey, consent with consentScope. Reuse unanswered questions. Saves checkpoint, blocked/uncertain status and task report atomically. On completion.taskReported=true stop without further calls. Reuse get_task_context from task start; do not reread it to ask.',inputSchema:object({question:str,jobId:str,resumeContext,fields:questionFieldsSchema,applicationBlocker},['question'])},
  {name:'record_submission',description:'Record observed external confirmation, not an attempted click. If the candidate account already shows an application for this exact vacancy, use kind=already_submitted directly from found/working/blocked: quote its applied message/date and application link in text/url; do not fake submitting or apply again. If documents are not visible say unknown, never invent them. Also durably completes the matching active application/verification task. When completion.taskReported=true, end the turn immediately: no update_application, report_campaign_work or extra success announcement tool call. Never fabricate proof or resubmit an uncertain application.',inputSchema:object({jobId:str,kind:{type:'string',enum:['success_page','confirmation_email','confirmation_message','already_submitted']},text:str,url:str,documents:str})}
];
import {validate} from '../../tool-schema.mjs';
import {startToolServer} from '../../tool-server.mjs';
export {validate};
export function applicationProtocol({store,browser,campaigns,onChange=()=>{}},grant){
 const {workspaceId:candidateId,sessionId}=grant;
 return {listTools:async()=>[...tools,...(browser?await browser.tools(candidateId):[])],async callResult(name,args){
 const rpc={params:{arguments:args}},result=value=>value;
      assertTaskTool(store.campaign(candidateId)?.task,name??'');
      if(store.workers(candidateId).length>1)assertWorkerAssignment(store,candidateId,name,rpc.params.arguments??{});
      const definition=tools.find(t=>t.name===name);if(!definition){if(browser&&name?.startsWith('browser_')){
        const response=await browser.call(candidateId,name,rpc.params.arguments??{},sessionId);
        // Bind rank failure evidence to observations from this candidate/session.
        const args=rpc.params.arguments??{};
        for(const part of response.content??[]){
          if(part.type!=='text')continue;
          let page;try{page=JSON.parse(part.text);}catch{continue;}
          if(page.browser!=='Jev Chrome'||!page.tabId||!page.observationId)continue;
          const session=grant;session.rankTabs??=new Map();session.rankObservations??=new Map();
          if(name==='browser_jev_open')session.rankTabs.set(page.tabId,args.url);
          session.rankObservations.set(page.observationId,{url:session.rankTabs.get(page.tabId)??page.url,at:Date.now()});
          if(session.rankObservations.size>40)session.rankObservations.delete(session.rankObservations.keys().next().value);
        }
        if(response.content?.some(part=>part.type==='text'&&(()=>{try{return JSON.parse(part.text).status==='browser_wait';}catch{return false;}})()))campaigns?.waitForBrowser?.(candidateId,{requested:true});
        return result(response);
      }throw Error('Unknown tool');}
      if(store.setup(candidateId)&&store.setup(candidateId).status!=='complete'&&['record_candidate_submission','defer_missing_documents','add_job','link_job_url','record_job_rank','update_application','record_validation_failure','continue_verification','record_submission','report_campaign_work'].includes(name))throw Error('Complete setup before job search or applications');
      const a=rpc.params.arguments??{};validate(definition.inputSchema,a);let value;
      if(workspaceTableTools.some(t=>t.name===name)){value=workspaceTableCall(store,candidateId,name,a);onChange(candidateId);return result({content:[{type:'text',text:JSON.stringify(value)}]});}
      if(['search','application','preparation','verify'].includes(store.campaign(candidateId)?.task?.kind)&&browser?.waiting?.(candidateId)&&['save_preparation','ask_candidate','update_application','save_application_checkpoint','report_campaign_work'].includes(name))return result({content:[{type:'text',text:JSON.stringify(browserWaitResult())}]});
      const reportedTask=name==='report_campaign_work'?(campaigns?.get?.(candidateId)??store.campaign(candidateId))?.task:null;
      const reviewTask=(campaigns?.get?.(candidateId)??store.campaign(candidateId))?.task?.id??`session:${sessionId}`;
      const saveReview=()=>store.saveTaskReview(candidateId,reviewTask,questionKnowledge(store,candidateId));
      switch(name){
        case 'save_preparation':value=await savePreparation(store,candidateId,a,sessionId);break;
        case 'resume_application':{
          const task=store.campaign(candidateId)?.task;
          const replyAction=store.taskContext(candidateId).candidateReplyActions.find(action=>action.tool!=='defer_missing_documents'||!task?.retryRequestId);
          if(task?.jobId===a.jobId&&replyAction)return result({content:[{type:'text',text:JSON.stringify({status:'candidate_reply_action',jobId:a.jobId,...replyAction})}]});
          if(!browser?.resumeApplication||store.profile(candidateId).browserMode!=='jev')throw Error('Bu araç Jev modu gerektirir; kayıtlı tarayıcı aracını kullan.');
          if(!['application','preparation','verify'].includes(task?.kind)||task.jobId!==a.jobId)throw Error('Yalnızca etkin başvuru sürdürülebilir.');
          if(!browser.prepare(candidateId).ready)return result({content:[{type:'text',text:JSON.stringify(browserWaitResult())}]});
          const job=store.job(candidateId,a.jobId);
          if(['found','blocked'].includes(job.status)&&['application','preparation'].includes(task.kind))store.updateJob(candidateId,a.jobId,'working','Kayıtlı başvuru devam noktası kontrol ediliyor',sessionId);
          const resumed=await browser.resumeApplication(candidateId,a.jobId,sessionId);onChange(candidateId);return result(resumed);
        }

        case 'update_setup_profile':value=store.updateSetupProfile(candidateId,a);break;
        case 'report_activity':value=store.reportActivity(candidateId,sessionId,a);break;
        case 'get_campaign':value=campaigns?.get?.(candidateId)??null;break;
        case 'report_campaign_work':if(!campaigns)throw Error('Campaign unavailable');{const task=(campaigns.get?.(candidateId)??store.campaign(candidateId))?.task;if(task?.kind==='search'&&['done','no_results','partial'].includes(a.outcome)&&!a.coverage)throw Error('Kaynak taramasını bitirmek için kapsam kanıtı gerekli. Kalan işi save_source_progress ile kaydet; tamamlanmadıysa partial bildir.');const saved=campaigns.report(candidateId,sessionId,a);value={status:saved.status,task:{id:saved.task.id,kind:saved.task.kind,report:saved.task.report},completion:{taskId:saved.task.id,taskReported:true,nextAction:'end_turn'}};}break;
        case 'save_source_progress':value=store.saveSourceProgress(candidateId,a.sourceId,a);break;
        case 'remember_candidate_fact':value=store.rememberFact(candidateId,a);break;
        case 'get_task_context':value={...store.taskContext(candidateId),browserStatus:browser?.status?.(candidateId)??null};saveReview();break;
        case 'get_candidate_profile':value=store.profile(candidateId);break;
        case 'list_applications':value=store.applicationHistory(candidateId,a);break;
        case 'check_jobs':value={jobs:store.checkJobs(candidateId,a.jobs).map(row=>({...row,needsResearch:!row.job||!['submitted','already_submitted','skipped','uncertain','submitting'].includes(row.job.status)&&row.job.rankDecision.state==='pending',job:row.job?jobReceipt(row.job,row.job.rankDecision):null}))};break;
        case 'link_job_url':{const saved=store.linkJobUrl(candidateId,a.jobId,a,sessionId);value={...saved,job:jobReceipt(saved.job,saved.job.rankDecision)};break;}
        case 'add_job':{const task=campaigns?.get?.(candidateId)?.task,saved=store.addJob(candidateId,{...a,sourceId:task?.kind==='search'?task.sourceId:null});value={duplicate:saved.duplicate,job:jobReceipt(saved.job,rankDecision(store.profile(candidateId),saved.job))};break;}
        case 'record_job_rank':{
          if(a.status==='unavailable'){
            const job=store.job(candidateId,a.jobId),check=a.browserCheck;
            const normalize=url=>{try{const u=new URL(url);u.hash='';return u.href;}catch{return null;}};
            if(!check||normalize(check.url)!==normalize(job.url))throw Error('Aynı kayıtlı ilan URL için tarayıcı kontrolü gerekli; WebFetch hatası yeterli değil.');
            if(store.profile(candidateId).browserMode==='jev'){
              const observation=grant.rankObservations?.get(check.observationId);
              if(check.backend!=='jev'||!observation||Date.now()-observation.at>600000||normalize(observation.url)!==normalize(job.url))throw Error('Bu oturumda aynı ilan için güncel Jev gözlemi gerekli. browser_jev_open ile ilanı aç, yüklenmesini kontrol et ve dönen observationId kullan.');
            }
          }
          const saved=store.rankJob(candidateId,a.jobId,a);value=jobReceipt(saved,rankDecision(store.profile(candidateId),saved));break;
        }
        case 'update_application':value=store.updateJob(candidateId,a.jobId,a.status,a.note,sessionId);break;
        case 'record_validation_failure':value=campaigns?.recordValidationFailure?campaigns.recordValidationFailure(candidateId,sessionId,a):store.recordValidationFailure(candidateId,a.jobId,a,sessionId);break;
        case 'continue_verification':value=store.continueVerification(candidateId,a.jobId,a,sessionId);break;
        case 'get_source_instructions':value=await sourceInstructions(sourceRoot,store.source(candidateId,a.sourceId));break;
        case 'run_source_tool':{const task=campaigns?.get?.(candidateId)?.task;if(campaigns?.get?.(candidateId)?.status!=='running'||task?.kind!=='search'||task.sourceId!==a.sourceId)throw Error('Araç yalnızca etkin kaynak taramasında çalıştırılabilir');value=await runSourceTool(sourceRoot,store.source(candidateId,a.sourceId),a.args);break;}
        case 'save_source_checkpoint':value=store.saveSourceCheckpoint(candidateId,a.sourceId,a);break;
        case 'save_application_checkpoint':value=store.saveApplicationCheckpoint(candidateId,a.jobId,a.resumeContext,sessionId);break;
        case 'resolve_technical_question':value=store.resolveTechnicalQuestion(candidateId,a.questionId,a.evidence);break;
        case 'ask_candidate':{const jobId=a.jobId??campaigns?.get?.(candidateId)?.task?.jobId;if(jobId&&!a.applicationBlocker)throw Error('İlan şartlarını doğrulatmak için soru sorma. Önce CV, profil ve kayıtlı yanıtları kullan. Yalnızca gerçekten zorunlu form alanı, erişim engeli veya mevcut izinlerin kapsamadığı onay için applicationBlocker içinde gözlenen alanı/engeli ve eksik bilgiyi belirt. Opsiyonel bilinmeyen alanı boş bırak.');validateQuestionInput(store,candidateId,jobId,a,store.taskReview(candidateId,reviewTask));const task=store.campaign(candidateId)?.task;value=campaigns?.askApplicationQuestion&&['application','preparation','verify'].includes(task?.kind)&&task.jobId===jobId?campaigns.askApplicationQuestion(candidateId,sessionId,{...a,jobId}):campaigns?.askCaptcha&&a.applicationBlocker?.kind==='access'&&a.applicationBlocker.recovery?.kind==='captcha'?campaigns.askCaptcha(candidateId,sessionId,{...a,jobId}):store.ask(candidateId,{...a,jobId},sessionId);break;}
        case 'record_candidate_submission':
        case 'defer_missing_documents':if(!campaigns?.recordCandidateReply)throw Error('Campaign unavailable');value=campaigns.recordCandidateReply(candidateId,sessionId,a,name);break;
        case 'stop_application_followup':if(!campaigns?.stopApplicationFollowup)throw Error('Campaign unavailable');value=campaigns.stopApplicationFollowup(candidateId,sessionId,a);break;
        case 'record_submission':value=campaigns?.recordSubmission?campaigns.recordSubmission(candidateId,sessionId,a):store.recordSubmission(candidateId,a.jobId,a,sessionId);break;
      }
      if(browser?.cleanup&&(name==='record_submission'||name==='record_candidate_submission'||name==='save_application_checkpoint'||name==='ask_candidate'||name==='update_application'&&a.status==='skipped')){
        const tabCleanup=await browser.cleanup(candidateId).catch(()=>({deferred:true}));value={...value,tabCleanup};
      }
      if(browser?.cleanupSearch&&name==='report_campaign_work'&&['search','rank'].includes(reportedTask?.kind)&&reportedTask.id===a.taskId&&['done','no_results'].includes(a.outcome)){
        const tabCleanup=await browser.cleanupSearch(candidateId,reportedTask.id).catch(()=>({deferred:true}));
        if(tabCleanup.closed?.length)store.clearSourceTabs(candidateId,tabCleanup.closed);
        value={...value,tabCleanup};
      }
      onChange(candidateId);return result({content:[{type:'text',text:JSON.stringify(value)}]});
 }};
}

export async function startMcp(rootStore,onChange=()=>{},onHook=async()=>({accepted:false}),rootBrowser=null,rootCampaigns=null,rootCustom=null,scope=null){
 return startToolServer({onHook,defaultWorkflow:rootCustom,assertOwner:id=>rootStore.profile(id),resolve(grant){
  const resolved=scope?.({...grant,candidateId:grant.workspaceId})??{store:rootStore,browser:rootBrowser,campaigns:rootCampaigns};
  return grant.workflow??applicationProtocol({...resolved,onChange},grant);
 }});
}
