const {contextBridge,ipcRenderer,webUtils}=require('electron');
const subscribe=(name,callback)=>{const listener=(_,value)=>callback(value);ipcRenderer.on(name,listener);return()=>ipcRenderer.removeListener(name,listener);};
contextBridge.exposeInMainWorld('jobloop',{
  backgroundCheckGmail:id=>ipcRenderer.invoke('background-check-gmail',id),backgroundConnectGmail:id=>ipcRenderer.invoke('background-connect-gmail',id),backgroundPickSkill:()=>ipcRenderer.invoke('background-pick-skill'),backgroundReadSkill:id=>ipcRenderer.invoke('background-read-skill',id),backgroundSnapshot:id=>ipcRenderer.invoke('background-snapshot',id),backgroundSave:(id,value)=>ipcRenderer.invoke('background-save',id,value),backgroundMessage:(id,text,runId)=>ipcRenderer.invoke('background-message',id,text,runId),backgroundRun:id=>ipcRenderer.invoke('background-run',id),backgroundStop:id=>ipcRenderer.invoke('background-stop',id),backgroundTerminal:(id,runId)=>ipcRenderer.invoke('background-terminal',id,runId),backgroundInput:(id,runId,text)=>ipcRenderer.invoke('background-input',id,runId,text),backgroundResize:(id,runId,rows,cols)=>ipcRenderer.invoke('background-resize',id,runId,rows,cols),resolveMailSignal:(id,signalId,jobId,outcome)=>ipcRenderer.invoke('resolve-mail-signal',id,signalId,jobId,outcome),dismissMailSignal:(id,signalId)=>ipcRenderer.invoke('dismiss-mail-signal',id,signalId),onBackgroundChange:callback=>subscribe('background-changed',callback),onBackgroundOutput:callback=>subscribe('background-output',callback),

  createSetup:settings=>ipcRenderer.invoke('create-setup',settings),beginSetup:(id,source)=>ipcRenderer.invoke('begin-setup',id,source),completeSetup:(id,fields)=>ipcRenderer.invoke('complete-setup',id,fields),importSetupCv:(id,file)=>ipcRenderer.invoke('import-setup-cv',id,webUtils.getPathForFile(file)),
  documents:id=>ipcRenderer.invoke('documents',id),readDocument:(id,file)=>ipcRenderer.invoke('read-document',id,file),openDocument:(id,file)=>ipcRenderer.invoke('open-document',id,file),
  catalog:()=>ipcRenderer.invoke('catalog'),promptCatalog:()=>ipcRenderer.invoke('prompt-catalog'),prompts:id=>ipcRenderer.invoke('prompts',id),candidates:()=>ipcRenderer.invoke('candidates'),snapshot:id=>ipcRenderer.invoke('snapshot',id),saveProfile:p=>ipcRenderer.invoke('save-profile',p),saveSource:(candidate,source)=>ipcRenderer.invoke('save-source',candidate,source),deleteSource:(candidate,id)=>ipcRenderer.invoke('delete-source',candidate,id),saveApplicationPolicy:(candidate,policy)=>ipcRenderer.invoke('save-application-policy',candidate,policy),pickCv:id=>ipcRenderer.invoke('pick-cv',id),start:(id,options)=>ipcRenderer.invoke('start',id,options),pause:id=>ipcRenderer.invoke('pause',id),stop:id=>ipcRenderer.invoke('stop',id),terminalOutput:id=>ipcRenderer.invoke('terminal-output',id),input:(id,text)=>ipcRenderer.invoke('terminal-input',id,text),resize:(id,rows,cols)=>ipcRenderer.invoke('terminal-resize',id,rows,cols),answer:(candidate,id,text)=>ipcRenderer.invoke('answer',candidate,id,text),reclaim:(candidate,id)=>ipcRenderer.invoke('reclaim',candidate,id),openLink:url=>ipcRenderer.invoke('open-link',url),onChange:callback=>subscribe('changed',callback),onAgentEvent:callback=>subscribe('agent-event',callback)
});
