import {Store} from '../app/store.mjs';
import {createRequire} from 'node:module';
import {mkdtemp,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url);
const {_electron:electron}=createRequire(require.resolve('@playwright/mcp/package.json'))('playwright');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const data=await mkdtemp(path.join((await import('node:os')).tmpdir(),'jobloop-ui-'));
const seed=new Store(path.join(data,'jobloop.sqlite'));seed.saveProfile({name:'Existing candidate',preferences:'Remote',authorization:'research'});seed.close();
const application=await electron.launch({executablePath:process.env.JOBLOOP_ELECTRON_BINARY||require('electron'),args:[root],env:{...process.env,JOBLOOP_DATA_DIR:data}});
try{
 const page=await application.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.locator('#now-panel').waitFor({state:'hidden'});
 await page.locator('button[data-view=profile]').click();
 await page.locator('#profile-form input[name=name]').fill('Demo Candidate');
 await page.locator('#profile-form textarea[name=preferences]').fill('Berlin hybrid, legal operations');
 await page.getByRole('button',{name:'Profili kaydet'}).click();
 await page.waitForFunction(()=>document.querySelector('#notice').textContent==='Profil kaydedildi.');
 await page.locator('button[data-view=agent]').click();
 await page.locator('#provider').selectOption('codex');
 await page.locator('#model').selectOption('gpt-5.6-sol');
 await page.locator('#permission').selectOption('plan');
 await page.locator('#reasoning').selectOption('high');
 await page.waitForFunction(()=>document.querySelector('#agent-settings-status').textContent.startsWith('Kaydedildi'));
 await page.reload();
 await page.locator('button[data-view=agent]').click();
 await page.waitForFunction(()=>document.querySelector('#model').value==='gpt-5.6-sol'&&document.querySelector('#permission').value==='plan'&&document.querySelector('#reasoning').value==='high');
 await page.locator('[name=browserMode]').selectOption('jev');
 await page.locator('#chrome-profile-field').waitFor({state:'visible'});
 await page.waitForFunction(()=>document.querySelector('#agent-settings-status').textContent.startsWith('Kaydedildi'));
 await page.reload();await page.locator('button[data-view=agent]').click();
 if(await page.locator('[name=browserMode]').inputValue()!=='jev')throw Error('Jev selection was not persisted');
 const jevProfile=await page.evaluate(async()=>{const c=(await window.jobloop.candidates())[0];return window.jobloop.snapshot(c.id);});
 if(jevProfile.profile.authorization!=='research'||jevProfile.profile.preferences!=='Berlin hybrid, legal operations')throw Error('Browser selection changed candidate scope');
 await page.locator('#provider').selectOption('claude');
 await page.locator('#model').selectOption('sonnet');
 await page.locator('#permission').selectOption('acceptEdits');
 await page.screenshot({path:path.join(data,'profile.png'),fullPage:true});
 await page.getByRole('button',{name:'Başvurular',exact:false}).click();
 await page.locator('#now-panel').waitFor({state:'hidden'});
 await page.locator('#terminal').waitFor({state:'hidden'});
 await page.locator('#campaign-target').fill('50');
 if(await page.locator('#campaign-interval').isVisible())await page.locator('#campaign-interval').fill('60');
 if(!await page.locator('#pause').isDisabled())throw Error('Inactive campaign pause must be disabled');
 const candidate=await page.evaluate(async()=> (await window.jobloop.candidates())[0].id);
 const docs=path.join(data,'candidates',candidate,'documents');await mkdir(docs,{recursive:true});await writeFile(path.join(docs,'letter.md'),'A natural cover letter. <script>plain text</script>');
 await page.locator('button[data-view=files]').click();
 await page.getByText('letter.md',{exact:true}).waitFor({timeout:12000});
 await page.getByRole('button',{name:'Önizle',exact:true}).click();
 if(await page.locator('#preview-content').textContent()!=='A natural cover letter. <script>plain text</script>')throw Error('Document preview did not preserve text');
 await page.getByRole('button',{name:'Kapat',exact:true}).click();
 const store=new Store(path.join(data,'jobloop.sqlite'));
 const job=store.addJob(candidate,{url:'https://example.com/jobs/test',company:'Test company',role:'Test role',location:'Berlin',fit:'Synthetic test'}).job;
 const other=store.addJob(candidate,{url:'https://example.com/jobs/other',company:'Test company',role:'Other role',location:'Berlin',fit:'Synthetic test'}).job;store.close();
 await mkdir(path.join(docs,`test-${job.id}`));await writeFile(path.join(docs,`test-${job.id}`,'cover-letter.md'),'Letter for this exact job');
 await page.reload();
 const jobFiles=page.locator(`[data-job-documents="${job.id}"]`);await jobFiles.getByText('Dosyalar (1)',{exact:true}).click();
 if(await page.locator(`[data-job-documents="${other.id}"]`).textContent()!=='')throw Error('Documents leaked into another job');
 await jobFiles.getByRole('button',{name:'Önizle',exact:true}).click();
 await page.locator('#document-preview').waitFor({state:'visible'});
 if(await page.locator('#preview-content').textContent()!=='Letter for this exact job')throw Error('Wrong application document');
 await page.getByRole('button',{name:'Kapat',exact:true}).click();
 await page.locator('button[data-view=agent]').click();
 await page.locator('#now-panel').waitFor({state:'visible'});
 await page.locator('#terminal').waitFor({state:'visible'});
 await page.locator('#now-history summary').click();
 for(const [width,height] of [[1100,740],[1440,950]]){
   await application.evaluate(({BrowserWindow},size)=>BrowserWindow.getAllWindows()[0].setSize(...size),[width,height]);
   await page.waitForFunction(()=>{const host=document.querySelector('#terminal'),surface=host.querySelector('.terminal-surface'),screen=host.querySelector('.xterm-screen');const h=host.getBoundingClientRect(),s=screen.getBoundingClientRect();return surface.clientHeight>200&&s.width>500&&s.right<=h.right+1&&s.bottom<=h.bottom+1&&s.height>=host.clientHeight-40;},null,{timeout:10000}).catch(async error=>{console.log(JSON.stringify(await page.locator("#terminal").evaluate(host=>({html:host.innerHTML.slice(0,500),rect:host.getBoundingClientRect().toJSON(),children:[...host.querySelectorAll(".terminal-surface,.xterm,.xterm-screen")].map(x=>({cls:x.className,rect:x.getBoundingClientRect().toJSON(),style:getComputedStyle(x).height}))})),null,2));throw error;});
 }
 await page.screenshot({path:path.join(data,'campaign.png'),fullPage:true});
 await page.locator('#new').click();
 await page.locator('#setup-begin').waitFor({state:'visible'});
 await page.locator('#setup-back').click();
 await page.locator('#onboarding').waitFor({state:'hidden'});
 // A running agent must not lock workspace selection; switching must keep it running.
 const switchingStore=new Store(path.join(data,'jobloop.sqlite'));
 const second=switchingStore.saveProfile({name:'Second candidate',preferences:'Berlin',authorization:'research'});switchingStore.close();
 const before=await page.evaluate(id=>window.jobloop.snapshot(id),candidate);
 const after=await page.evaluate(id=>window.jobloop.snapshot(id),second.id);
 await application.evaluate(({ipcMain},{before,after})=>{
  globalThis.workspacePaused=false;
  ipcMain.removeHandler('snapshot');ipcMain.handle('snapshot',(_,id)=>id===before.profile.id?{...before,active:globalThis.workspacePaused?null:{candidateId:id,sessionId:'test-session',state:'Working'},campaign:{status:globalThis.workspacePaused?'paused':'running',target:100,intervalMinutes:30,note:'Test'}}:after);
  ipcMain.removeHandler('pause');ipcMain.handle('pause',(_,id)=>{if(id!==before.profile.id)throw Error('Wrong workspace paused');globalThis.workspacePaused=true;});
 },{before,after});
 await page.reload();
 await page.waitForFunction(()=>document.querySelector('#agent-nav-status').textContent==='Çalışıyor');
 if(await page.locator('#candidates').isDisabled())throw Error('Working agent locked workspace selector');
 await page.locator('#candidates').selectOption(second.id);
 await page.waitForFunction(()=>document.querySelector('#heading').textContent.startsWith('Second,'));
 if(await application.evaluate(()=>globalThis.workspacePaused))throw Error('Workspace switching paused an agent');
 if(await page.locator('#agent-nav-status').textContent()!=='Kapalı')throw Error('Old agent status leaked into new workspace');
 await page.locator('#candidates').selectOption(candidate);await page.waitForFunction(()=>document.querySelector('#agent-nav-status').textContent==='Çalışıyor');
 if(errors.length)throw Error(errors.join('\n'));
 console.log('UI_SMOKE_PASS',data);
}finally{await application.close();}
