import {rankInput} from '../tests/rank-fixture.mjs';
import {Store} from '../app/store.mjs';
import {createRequire} from 'node:module';
import {mkdtemp,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const require=createRequire(import.meta.url);
const {_electron:electron}=createRequire(require.resolve('@playwright/mcp/package.json'))('playwright');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const data=await mkdtemp(path.join((await import('node:os')).tmpdir(),'jobloop-ui-'));
const seed=new Store(path.join(data,'jobloop.sqlite'));seed.saveProfile({name:'Existing candidate',preferences:'Remote',authorization:'research'});seed.close();
const application=await electron.launch({executablePath:process.env.JOBLOOP_ELECTRON_BINARY||require('electron'),args:[root],env:{...process.env,JOBLOOP_DATA_DIR:data}});
try{
 const page=await application.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 // Exercise real IPC and scheduling without starting a provider or browsing.
 await application.evaluate(async(_,urls)=>{
  const vm=process.getBuiltinModule('node:vm'),load=vm.runInThisContext('(url)=>import(url)',{importModuleDynamically:vm.constants.USE_MAIN_CONTEXT_DEFAULT_LOADER});
  const {Engine}=await load(urls.engine),{BrowserTools}=await load(urls.browser),request=Engine.prototype.request;
  globalThis.agentStarts=0;
  Engine.prototype.request=function(op,args={}){if(op==='start')globalThis.agentStarts++;if(['start','message','resize'].includes(op))return Promise.resolve({});return request.call(this,op,args);};
  BrowserTools.prototype.prepare=()=>({state:'ready',ready:true});
 },{engine:pathToFileURL(path.join(root,'app/engine.mjs')).href,browser:pathToFileURL(path.join(root,'app/browser.mjs')).href});
 await page.waitForFunction(()=>Boolean(document.querySelector('#candidates').value));
 await page.locator('#now-panel').waitFor({state:'hidden'});
 await page.locator('#rename-workspace').waitFor();
 await page.locator('button[data-view=profile]').click();
 await page.locator('#profile-form input[name=name]').fill('Demo Candidate');
 await page.locator('#profile-form textarea[name=preferences]').fill('Berlin hybrid, legal operations');
 await page.getByRole('button',{name:'Profili kaydet'}).click();
 await page.waitForFunction(()=>document.querySelector('#notice').textContent==='Profil kaydedildi.');
 const originalWorkspace=await page.locator('#candidates').inputValue();
 await page.locator('#rename-workspace').click();
 await page.locator('#rename-workspace-dialog input').fill('Berlin applications');
 await page.locator('#rename-workspace-dialog button[type=submit]').click();
 await page.waitForFunction(()=>document.querySelector('#candidates').selectedOptions[0]?.textContent==='Berlin applications');
 await page.reload();
 await page.waitForFunction(()=>document.querySelector('#candidates').selectedOptions[0]?.textContent==='Berlin applications');
 if(await page.locator('#profile-form input[name=name]').inputValue()!=='Demo Candidate')throw Error('Workspace rename changed candidate identity');
 const removableStore=new Store(path.join(data,'jobloop.sqlite'));
 const removable=removableStore.saveProfile({name:'Temporary candidate',preferences:'Remote'});removableStore.close();
 const removableDir=path.join(data,'candidates',removable.id);await mkdir(removableDir,{recursive:true});await writeFile(path.join(removableDir,'note.txt'),'Temporary workspace file');
 await page.reload();await page.locator('#candidates').selectOption(removable.id);
 page.once('dialog',dialog=>dialog.accept());
 await page.locator('#delete-workspace').click();
 await page.waitForFunction(id=>![...document.querySelector('#candidates').options].some(option=>option.value===id),removable.id);
 const deletedStore=new Store(path.join(data,'jobloop.sqlite'));
 if(deletedStore.candidates().some(p=>p.id===removable.id))throw Error('Deleted workspace remains in database');deletedStore.close();
 if(await import('node:fs/promises').then(fs=>fs.stat(removableDir).then(()=>true,()=>false)))throw Error('Deleted workspace files remain');
 const removableAutomation=await page.evaluate(async()=>window.jobloop.workspaceCreate('custom',{title:'Temporary automation'}));
 await page.reload();await page.locator('#candidates').selectOption('automation:'+removableAutomation.id);
 await page.evaluate(id=>window.jobloop.automationMessage(id,'Find a suitable home'),removableAutomation.id);
 await page.waitForFunction(id=>document.querySelector('#candidates').value==='automation:'+id&&!document.querySelector('#delete-workspace').disabled,removableAutomation.id);
 await page.locator('button[data-view=profile]').click();
 page.once('dialog',dialog=>dialog.accept());
 await page.locator('#automation-delete').click();
 await page.waitForFunction(id=>![...document.querySelector('#candidates').options].some(option=>option.value==='automation:'+id),removableAutomation.id);
 await application.evaluate(()=>{globalThis.agentStarts=0;});
 await page.locator('#candidates').selectOption(originalWorkspace);
 await page.locator('button[data-view=agent]').click();
 await page.locator('#provider').selectOption('codex');
 await page.locator('#model').selectOption('gpt-5.6-sol');
 await page.locator('#permission').selectOption('plan');
 await page.locator('#reasoning').selectOption('high');
 await page.locator('[name=contextRestartPercent]').fill('16');
 await page.locator('[name=contextRestartPercent]').press('Tab');
 await page.locator('#agent-settings-save').click();
 await page.waitForFunction(()=>document.querySelector('#agent-settings-status').textContent.startsWith('Kaydedildi'));
 await page.reload();
 await page.locator('button[data-view=agent]').click();
 await page.waitForFunction(()=>document.querySelector('#model').value==='gpt-5.6-sol'&&document.querySelector('#permission').value==='plan'&&document.querySelector('#reasoning').value==='high');
 if(await page.locator('[name=contextRestartPercent]').inputValue()!=='16')throw Error('Context threshold was not persisted');
 await page.locator('[name=browserMode]').selectOption('jev');
 await page.locator('#chrome-profile-field').waitFor({state:'visible'});
 await page.locator('#agent-settings-save').click();
 await page.waitForFunction(()=>document.querySelector('#agent-settings-status').textContent.startsWith('Kaydedildi.'));
 await page.reload();await page.locator('button[data-view=agent]').click();
 if(await page.locator('[name=browserMode]').inputValue()!=='jev')throw Error('Jev selection was not persisted');
 await page.locator('.chrome-status').waitFor({state:'visible'});
 if(!await page.locator('.chrome-status b').textContent().then(text=>text.includes('Chrome')))throw Error('Chrome connection status missing');
 const jevProfile=await page.evaluate(async()=>{const c=(await window.jobloop.candidates())[0];return window.jobloop.workspaceSnapshot(c.id);});
 if(jevProfile.profile.authorization!=='research'||jevProfile.profile.preferences!=='Berlin hybrid, legal operations')throw Error('Browser selection changed candidate scope');
 await page.locator('#provider').selectOption('claude');
 await page.locator('#model').selectOption('sonnet');
 await page.locator('#permission').selectOption('acceptEdits');
 await page.locator('#agent-settings-save').click();
 await page.waitForFunction(()=>document.querySelector('#agent-settings-status').textContent.startsWith('Kaydedildi'));
 const contextSettings=await page.evaluate(async()=>{const c=(await window.jobloop.candidates())[0];return (await window.jobloop.workspaceSnapshot(c.id)).profile.agentSettings;});
 if(contextSettings.provider!=='claude'||contextSettings.contextRestartPercent!==16)throw Error('Claude did not retain the context threshold');
 await page.screenshot({path:path.join(data,'profile.png'),fullPage:true});
 await page.getByRole('button',{name:'Başvurular',exact:false}).click();
 await page.locator('#now-panel').waitFor({state:'hidden'});
 await page.locator('#terminal').waitFor({state:'hidden'});
 await page.locator('#campaign-target').fill('50');
 if(await page.locator('#campaign-interval').isVisible())await page.locator('#campaign-interval').fill('60');
 if(await page.locator('#pause, #now-pause, #now-write').count())throw Error('Duplicate agent controls remain');
 if(await page.locator('#stop').isVisible())throw Error('Inactive agent stop must be hidden');
 if(!await page.locator('#restart-agent').isVisible())throw Error('Fresh restart control missing');
 const candidate=await page.evaluate(async()=> (await window.jobloop.candidates())[0].id);
 const docs=path.join(data,'candidates',candidate,'documents');await mkdir(docs,{recursive:true});await writeFile(path.join(docs,'letter.md'),'A natural cover letter. <script>plain text</script>');
 await page.locator('button[data-view=files]').click();
 await page.getByText('letter.md',{exact:true}).waitFor({timeout:12000});
 await page.getByRole('button',{name:'Önizle',exact:true}).click();
 if(await page.locator('#preview-content').textContent()!=='A natural cover letter. <script>plain text</script>')throw Error('Document preview did not preserve text');
 await page.getByRole('button',{name:'Kapat',exact:true}).click();
 const store=new Store(path.join(data,'jobloop.sqlite'));
 const cv=path.join(data,'cv.txt');await writeFile(cv,'Synthetic UI candidate');store.setCv(candidate,cv);
 const job=store.addJob(candidate,{url:'https://example.com/jobs/test',company:'Test company',role:'Test role',location:'Berlin',fit:'Synthetic test'}).job;
 const other=store.addJob(candidate,{url:'https://example.com/jobs/other',company:'Test company',role:'Other role',location:'Berlin',fit:'Synthetic test'}).job;
 store.saveProfile({...store.profile(candidate),authorization:'prepare'});
 const waiting=store.addJob(candidate,{url:'https://example.com/jobs/waiting',company:'Waiting company',role:'Waiting role',location:'Berlin',fit:'Synthetic test'}).job;
 store.rankJob(candidate,waiting.id,rankInput(store,candidate));
 store.updateJob(candidate,waiting.id,'working','Form','test');store.updateJob(candidate,waiting.id,'blocked','Needs date','test');
 const question=store.ask(candidate,{jobId:waiting.id,question:'Start date?'});
 const reported=store.addJob(candidate,{url:'https://example.com/jobs/reported',company:'Reported company',role:'Reported role',location:'Berlin',fit:'Synthetic test'}).job;
 const sentReply=store.ask(candidate,{jobId:reported.id,question:'Başvuru durumu?'});store.answer(candidate,sentReply.id,'Başvurdum');store.recordCandidateReply(candidate,reported.id,sentReply.id,'test','record_candidate_submission');
 const held=store.addJob(candidate,{url:'https://example.com/jobs/documents',company:'Documents company',role:'Documents role',location:'Berlin',fit:'Synthetic test'}).job;
 const noFiles=store.ask(candidate,{jobId:held.id,question:'Transkript dosyası var mı?',applicationBlocker:{kind:'required_form_field',evidence:'Transcript PDF required'}});store.answer(candidate,noFiles.id,'yok');store.recordCandidateReply(candidate,held.id,noFiles.id,'test','defer_missing_documents');
 const inaccessible=store.addJob(candidate,{url:'https://example.com/jobs/inaccessible',company:'Inaccessible company',role:'Engineer',location:'Berlin',fit:'Test'}).job;
 store.rankJob(candidate,inaccessible.id,{profileKey:store.profile(candidate).rankingProfileKey,status:'unavailable',summary:'Browser denied access',browserCheck:{backend:'existing',url:inaccessible.url,evidence:'Browser denied access'}});
 const existing=store.addJob(candidate,{url:'https://example.com/jobs/existing',company:'Existing company',role:'Lead',location:'Berlin',fit:'Test'}).job;
 store.recordSubmission(candidate,existing.id,{kind:'already_submitted',text:'You already applied',url:'https://example.com/application',documents:'Unknown'},'test');store.close();
 await mkdir(path.join(docs,`test-${job.id}`));await writeFile(path.join(docs,`test-${job.id}`,'cover-letter.md'),'Letter for this exact job');
 await page.reload();
 await page.getByText('Gönderildi · Kullanıcı beyanı',{exact:true}).waitFor();
 await page.getByText('Belge bekliyor',{exact:true}).waitFor();
 const inaccessibleRow=page.locator('tr').filter({hasText:'Inaccessible company'});
 await inaccessibleRow.getByRole('button',{name:'Yeniden incele',exact:true}).click();
 await inaccessibleRow.getByRole('button',{name:'İnceleme sırasında',exact:true}).waitFor();
 const existingRow=page.locator('tr').filter({hasText:'Existing company'});
 await existingRow.locator('.badge').filter({hasText:'Gönderildi'}).waitFor();
 if(await existingRow.locator('select').isDisabled())throw Error('Manual status must remain enabled for confirmed applications');
 await existingRow.locator('select').selectOption('withdrawn');
 await existingRow.locator('.badge').filter({hasText:'Vazgeçildi'}).waitFor();
 const jobFiles=page.locator(`[data-job-documents="${job.id}"]`);await jobFiles.getByText('Dosyalar (1)',{exact:true}).click();
 if(await page.locator(`[data-job-documents="${other.id}"]`).textContent()!=='')throw Error('Documents leaked into another job');
 await jobFiles.getByRole('button',{name:'Önizle',exact:true}).click();
 await page.locator('#document-preview').waitFor({state:'visible'});
 if(await page.locator('#preview-content').textContent()!=='Letter for this exact job')throw Error('Wrong application document');
 await page.getByRole('button',{name:'Kapat',exact:true}).click();
 const queue=page.getByRole('button',{name:'Waiting company başvurusunu sıraya al',exact:true});
 await queue.click();await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(b=>b.textContent==='İşleniyor'&&b.disabled));
 await page.waitForFunction(()=>document.querySelector('#campaign-status').textContent.includes('Görev kuyrukta'));
 const queued=await page.evaluate(id=>window.jobloop.workspaceSnapshot(id),candidate);
 if(!queued.campaign.pendingRetries[waiting.id]||queued.campaign.status!=='running'||queued.campaign.task?.jobId!==waiting.id||!queued.active)throw Error('Queue did not start the agent for the selected job');
 if(await application.evaluate(()=>globalThis.agentStarts)!==1)throw Error('Queue started duplicate agents');
 if(queued.questions.find(q=>q.id===question.id).answer!==null)throw Error('Queue answered candidate question');
 await page.reload();await queue.waitFor();if(!await queue.isDisabled()||await queue.textContent()!=='İşleniyor')throw Error('Active queue state did not survive reload');
 await page.evaluate(id=>window.jobloop.workspaceStop(id),candidate);
 await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(b=>b.getAttribute('aria-label')==='Waiting company başvurusunu sıraya al'&&b.disabled&&b.textContent==='Öncelikli sırada'));
 await page.locator('#start').click();await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(b=>b.textContent==='İşleniyor'&&b.disabled));
 await page.waitForFunction(()=>document.querySelector('#campaign-status').textContent.includes('Görev kuyrukta'));
 if(await application.evaluate(()=>globalThis.agentStarts)!==2)throw Error('Previously queued job did not restart the stopped agent');
 await page.evaluate(id=>window.jobloop.workspaceStop(id),candidate);
 await page.locator('button[data-view=sources]').click();
 const source=queued.sources.find(s=>s.enabled),toggle=page.getByRole('checkbox',{name:`${source.name} aktif`,exact:true});
 await toggle.uncheck();await page.waitForFunction(sourceId=>{const input=document.querySelector(`[data-source-id="${sourceId}"] input[type=checkbox]`);return input&&!input.checked&&!input.disabled;},source.id);
 if((await page.evaluate(id=>window.jobloop.workspaceSnapshot(id),candidate)).campaign.status!=='stopped')throw Error('Disabling source started the agent');
 await toggle.check();await page.waitForFunction(()=>document.querySelector('#campaign-status').textContent.includes('Görev kuyrukta'));
 if(await application.evaluate(()=>globalThis.agentStarts)!==3)throw Error('Enabling source did not start exactly one agent');
 await page.evaluate(id=>window.jobloop.workspaceStop(id),candidate);
 await page.locator('button[data-view=agent]').click();
 await page.locator('#now-panel').waitFor({state:'visible'});
 await page.locator('#terminal').waitFor({state:'hidden'});
 await page.locator('#now-history summary').click();
 await page.evaluate(id=>window.jobloop.startWorker(id,'main'),candidate);
 // Chat is the default view; the terminal checks below need the terminal lens.
 await page.locator('.worker-pane[data-worker-id=main][data-view=chat] .worker-chat').waitFor({state:'visible'});
 await page.locator('.worker-pane[data-worker-id=main]').getByRole('tab',{name:'Terminal'}).click();await page.locator('#terminal').waitFor({state:'visible'});
 for(const [width,height] of [[1100,740],[1440,950]]){
   await application.evaluate(({BrowserWindow},size)=>BrowserWindow.getAllWindows()[0].setSize(...size),[width,height]);
   await page.waitForFunction(()=>{const host=document.querySelector('#terminal'),surface=host.querySelector('.terminal-surface'),screen=host.querySelector('.xterm-screen');const h=host.getBoundingClientRect(),s=screen.getBoundingClientRect();return surface.clientHeight>200&&s.width>500&&s.right<=h.right+1&&s.bottom<=h.bottom+1&&s.height>=host.clientHeight-40;},null,{timeout:10000}).catch(async error=>{console.log(JSON.stringify(await page.locator("#terminal").evaluate(host=>({html:host.innerHTML.slice(0,500),rect:host.getBoundingClientRect().toJSON(),children:[...host.querySelectorAll(".terminal-surface,.xterm,.xterm-screen")].map(x=>({cls:x.className,rect:x.getBoundingClientRect().toJSON(),style:getComputedStyle(x).height}))})),null,2));throw error;});
 }
 await page.screenshot({path:path.join(data,'campaign.png'),fullPage:true});
 // The chat view shows saved records instead of terminal bytes and survives a reload.
 const mainPane=page.locator('.worker-pane[data-worker-id=main]');
 await mainPane.getByRole('tab',{name:'Sohbet'}).click();
 await mainPane.locator('.worker-chat').waitFor({state:'visible'});
 if(await mainPane.locator('.worker-terminal').isVisible())throw Error('Terminal stayed visible in chat view');
 await mainPane.locator('.worker-chat-entry, .worker-chat-empty').first().waitFor({state:'visible'});
 await page.screenshot({path:path.join(data,'worker-chat.png'),fullPage:true});
 await page.reload();await page.locator('button[data-view=agent]').click();
 await page.locator('.worker-pane[data-worker-id=main][data-view=chat] .worker-chat').waitFor({state:'visible'});
 await page.locator('.worker-pane[data-worker-id=main]').getByRole('tab',{name:'Terminal'}).click();
 await page.locator('#terminal').waitFor({state:'visible'});
 await page.waitForFunction(()=>{const host=document.querySelector('#terminal'),screen=host.querySelector('.xterm-screen');if(!screen)return false;const h=host.getBoundingClientRect(),s=screen.getBoundingClientRect();return s.width>500&&s.right<=h.right+1&&s.bottom<=h.bottom+1;},null,{timeout:10000});
 await page.reload();await page.locator('button[data-view=agent]').click();
 await page.locator('.worker-pane[data-worker-id=main][data-view=terminal]').waitFor();
 await page.evaluate(()=>{for(const key of Object.keys(localStorage))if(key.startsWith('worker-view:'))localStorage.removeItem(key);});
 await page.reload();await page.locator('button[data-view=agent]').click();
 await page.locator('.worker-pane[data-worker-id=main][data-view=chat] .worker-chat').waitFor({state:'visible'});
 await page.evaluate(id=>window.jobloop.workspaceStop(id),candidate);
 await page.locator('button[data-view=templates]').click();await page.locator('[data-template=job-search]').click();
 await page.locator('#setup-begin').waitFor({state:'visible'});
 await page.locator('#setup-back').click();
 await page.locator('#onboarding').waitFor({state:'hidden'});
 // The original applications table uses the same schema/cells as other templates.
 const tableStore=new Store(path.join(data,'jobloop.sqlite')),tableJob=tableStore.jobs(candidate)[0];
 tableStore.workspaces.configureTable(candidate,{title:'Başvurular',columns:[{key:'source',label:'Şirket',type:'text'},{key:'title',label:'Pozisyon',type:'text'},{key:'salary',label:'Maaş (€)',type:'money'}]});
 tableStore.workspaces.updateCells(candidate,tableJob.id,[{key:'salary',value:'65000'}]);tableStore.close();
 await page.reload();await page.locator('[data-view=board]').click();await page.locator('#jobs th[data-column=salary]').waitFor();
 if(!await page.locator('#jobs td[data-column=salary]').allTextContents().then(values=>values.includes('65.000,00')))throw Error('Shared typed table cell missing from jobs');
 // A running agent must not lock workspace selection; switching must keep it running.
 const switchingStore=new Store(path.join(data,'jobloop.sqlite'));
 const second=switchingStore.saveProfile({name:'Second candidate',preferences:'Berlin',authorization:'research'});switchingStore.close();
 const before=await page.evaluate(id=>window.jobloop.workspaceSnapshot(id),candidate);
 const after=await page.evaluate(id=>window.jobloop.workspaceSnapshot(id),second.id);
 await application.evaluate(({ipcMain},{before,after})=>{
  globalThis.workspacePaused=false;
  ipcMain.removeHandler('workspace-snapshot');ipcMain.handle('workspace-snapshot',(_,id)=>id===before.profile.id?{...before,active:globalThis.workspacePaused?null:{candidateId:id,sessionId:'test-session',state:'Working'},campaign:{status:globalThis.workspacePaused?'paused':'running',target:100,intervalMinutes:30,note:'Test'}}:after);
  ipcMain.removeHandler('workspace-stop');ipcMain.handle('workspace-stop',(_,id)=>{if(id!==before.profile.id)throw Error('Wrong workspace paused');globalThis.workspacePaused=true;});
 },{before,after});
 await page.reload();
 if(await page.locator('#automations').isVisible())await page.locator(`[data-automation-job="${candidate}"]`).click();
 await page.waitForFunction(()=>document.querySelector('#agent-nav-status').textContent==='Çalışıyor');
 if(await page.locator('#start').isVisible()||!await page.locator('#stop').isVisible())throw Error('Running agent controls incorrect');
 if(await page.locator('#candidates').isDisabled())throw Error('Working agent locked workspace selector');
 await page.locator('#candidates').selectOption(second.id);
 await page.waitForFunction(()=>document.querySelector('#heading').textContent.startsWith('Second,'));
 if(await application.evaluate(()=>globalThis.workspacePaused))throw Error('Workspace switching paused an agent');
 if(await page.locator('#agent-nav-status').textContent()!=='Kapalı')throw Error('Old agent status leaked into new workspace');
 await page.locator('#candidates').selectOption(candidate);await page.waitForFunction(()=>document.querySelector('#agent-nav-status').textContent==='Çalışıyor');
 await application.evaluate(({ipcMain},{before})=>{ipcMain.removeHandler('workspace-snapshot');ipcMain.handle('workspace-snapshot',()=>({...before,browserStatus:{state:'waiting',ready:false,message:'Synthetic disconnect'},active:null}));},{before});
 await page.reload();await page.getByText('Chrome bağlantısı bekleniyor',{exact:true}).waitFor();
 await page.screenshot({path:path.join(data,'chrome-waiting.png'),fullPage:true});
 await application.evaluate(({ipcMain},{before})=>{ipcMain.removeHandler('workspace-snapshot');ipcMain.handle('workspace-snapshot',()=>({...before,browserStatus:{state:'ready',ready:true},active:null}));},{before});
 await page.reload();await page.getByText('Chrome bağlı',{exact:true}).waitFor();
 if(await page.getByRole('button',{name:'Yeniden bağlan',exact:true}).isVisible())throw Error('Reconnect shown while connected');
 if(errors.length)throw Error(errors.join('\n'));
 console.log('UI_SMOKE_PASS',data);
}finally{await application.close();}
