import {defaultPermission} from '../app/agent-settings.mjs';
import './background.css';
const legacyOutcomes={confirmation:'Başvuru alındı',interview:'Mülakat daveti',assessment:'Değerlendirme / test',offer:'Teklif',rejection:'Olumsuz dönüş',unmatched:'Eşleştirme gerekli'};
const states={running:'Çalışıyor',completed:'Tamamlandı',failed:'Hata',timeout:'Süre aşıldı',cancelled:'Durduruldu',interrupted:'Kesildi',blocked:'İşlem gerekiyor'};
const verbs={completed:'tamamlandı',failed:'hata verdi',timeout:'süre aşımına uğradı',cancelled:'durduruldu',interrupted:'kesildi',blocked:'işlem bekliyor'};
const phases={Starting:'Başlatılıyor',None:'Bağlantı / onay bekleniyor',Working:'İşleniyor',Idle:'Hazır',AwaitingInput:'Onay bekliyor',Compacting:'Özetleniyor'};
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e;};
const millis=value=>typeof value==='number'?value:Date.parse(value)||0;
const time=value=>millis(value)?new Date(millis(value)).toLocaleString('tr-TR'):'—';
function relative(value,{past=false,now=Date.now()}={}){const ms=millis(value);if(!ms)return '—';const minutes=Math.round(Math.abs(past?now-ms:ms-now)/60000);if(minutes<1)return past?'az önce':'şimdi';const unit=minutes<60?`${minutes} dk`:minutes<1440?`${Math.round(minutes/60)} sa`:`${Math.round(minutes/1440)} gün`;return `${unit} ${past?'önce':'sonra'}`;}
function when(value,options){const node=el('time',relative(value,options));node.title=time(value);return node;}
const fold=value=>String(value??'').toLocaleLowerCase('tr').normalize('NFKD').replace(/[̀-ͯ]/g,'').replace(/ı/g,'i').replace(/[^a-z0-9]+/g,' ').trim();
const commonWords=new Set(['gmbh','inc','ltd','llc','ag','se','sa','bv','group','labs','the','and','und','company','technologies','technology','software','engineer','engineering','senior','staff','lead','principal','backend','frontend','remote','europe','germany','berlin','with','mit','for','fur']);
function matchScore(job,text){if(!text)return 0;const padded=` ${text} `,company=fold(job.company);let score=0;if(company&&padded.includes(` ${company} `))score+=10;else for(const word of company.split(' '))if(word.length>2&&!commonWords.has(word)&&padded.includes(` ${word} `))score+=5;if(!score)return 0;for(const word of new Set(fold(job.role).split(' ')))if(word.length>2&&!commonWords.has(word)&&padded.includes(` ${word} `))score+=1;return score;}
function guessOutcome(signal){const text=fold(`${signal.subject} ${signal.summary}`);if(/\b(ret|reddet|olumsuz|absage|reject|unfortunately|leider|not moving forward|other candidates)/.test(text))return 'rejection';if(/\b(mulakat|interview|gorusme|vorstellungsgesprach|kennenlernen)/.test(text))return 'interview';if(/\b(teklif|offer|angebot)\b/.test(text))return 'offer';if(/\b(test|assessment|coding challenge|case study|degerlendirme)/.test(text))return 'assessment';if(/\b(onay|received|eingegangen|thank you for applying|bewerbung erhalten|alindi)/.test(text))return 'confirmation';return '';}
const jobStates={found:'Bulundu',working:'Üzerinde çalışılıyor',prepared:'Gönderime hazır',submitting:'Gönderiliyor',submitted:'Gönderildi',blocked:'İşlem bekliyor',uncertain:'Doğrulanmalı',skipped:'Elendi'};
function appLabel(job){const node=el('span',null,'app-label');node.append(el('b',job.company),el('span',job.role,'app-label-role'));if(job.status)node.append(el('small',jobStates[job.status]??job.status,'app-label-status'));node.title=`${job.company} · ${job.role}`;return node;}
export function backgroundPage(api,{notice,getCatalog}){
 const host=document.getElementById('background');const drafts=new Map();let candidate=null,data=null,selectedRun=null,formCandidate=null,outcomes=legacyOutcomes;
 host.innerHTML=`<div class="background-head"><h2>Background Jobs</h2><p>Uygulama açıkken ayrı bir agent, seçtiğin skill’i belirlediğin aralıkla çalıştırır ve bitince kapanır. Gelen sonuçlar bu sayfada toplanır; model ve izinleri Ayarlar’dan seçebilirsin.</p></div>
<section id="background-status" class="background-status" data-tone="off" aria-label="Arka plan görevinin durumu"><div class="background-status-top"><div class="background-status-copy"><div class="background-status-label"><span id="background-summary"></span></div><h2 id="background-title"></h2><p id="background-detail"></p><small id="background-last"></small></div><div class="background-status-actions"><button id="background-run" class="quiet" type="button">Şimdi çalıştır</button><button id="background-stop" class="quiet" type="button">Durdur</button><button id="background-settings" class="quiet" type="button" aria-expanded="false" aria-controls="background-form">Ayarlar</button></div></div>
<div id="gmail-access" class="gmail-access"><p id="gmail-access-message"></p><div class="actions"><button id="gmail-check" type="button" class="quiet">Bağlantıyı kontrol et ve yeniden dene</button><button id="gmail-connect" type="button" class="primary" hidden>Gmail’i bağla ↗</button></div></div>
<form id="background-form" class="background-form" hidden><div class="background-skill"><span>Çalıştırılacak skill</span><input name="skillPath" type="hidden"><b id="background-skill-name">gmail-sync / SKILL.md</b><div class="background-skill-actions"><button id="background-pick-skill" type="button" class="quiet">Dosya seç</button><button id="background-default-skill" type="button" class="quiet">Gmail sync kullan</button></div><details id="background-skill-details"><summary>Skill içeriğini göster</summary><pre id="background-skill-content"></pre></details></div><div class="background-schedule"><label class="background-toggle"><input name="enabled" type="checkbox" class="switch"><span>Düzenli çalıştır<small>Uygulama açıkken belirlediğin aralıkla tekrarlar.</small></span></label><label>Çalışma aralığı (dakika)<input name="intervalMinutes" type="number" min="1" max="10080" required></label></div><div class="background-agent-settings"><label class="background-toggle"><input name="inheritAgent" type="checkbox" class="switch"><span>Çalışma alanının agent ayarlarını kullan</span></label><div id="background-agent-options" class="settings-grid"><label>Sağlayıcı<select name="provider"></select></label><label>Model<select name="model"></select></label><label>İzin modu<select name="permission"></select></label><label>Düşünme seviyesi<select name="reasoning"></select></label><label>Ağ erişimi<select name="network"><option value="inherit">Varsayılan</option><option value="true">İzin ver</option><option value="false">Kapat</option></select></label></div><small>Kaydedilen ayarlar bir sonraki oturumda uygulanır. Claude, kendi Gmail MCP bağlantısını kullanır.</small></div><div class="background-form-foot"><button class="primary" type="submit">Kaydet</button><button id="background-settings-cancel" class="quiet" type="button">Vazgeç</button><span id="background-next"></span></div></form></section>
<form id="background-chat" class="background-chat"><label for="background-chat-message">Görev agent’ına mesaj</label><textarea id="background-chat-message" maxlength="12000" required placeholder="Arka plan görevi hakkında yaz…"></textarea><div class="actions"><button type="submit" class="primary" id="background-chat-send">Gönder</button><span id="background-chat-hint"></span></div></form>
<div class="section-title"><h2>Gelen sonuçlar</h2><span id="background-signals-note"></span></div><div id="background-signals"></div>
<section id="background-history" class="background-history" hidden><div class="section-title"><h2>Çalışma geçmişi</h2></div><div id="background-runs" class="run-list"></div></section>`;
 const $=id=>document.getElementById(id),form=$('background-form'),fields=form.elements;
 const attempt=fn=>async(...args)=>{try{await fn(...args);}catch(error){notice(error.message);}};
 const skillLabel=value=>value?value.split(/[\\/]/).slice(-2).join(' / '):'gmail-sync / SKILL.md';
 function skillName(){ $('background-skill-name').textContent=skillLabel(fields.skillPath.value);$('background-skill-name').title=fields.skillPath.value; }
 function agentOptions(saved){const current=getCatalog().find(a=>a.id===fields.provider.value);for(const [key,list]of [['model',current?.models??[]],['permission',current?.permissions??[]],['reasoning',current?.reasoning??[]]]){fields[key].replaceChildren(...list.map(value=>new Option(value,value)));fields[key].value=list.includes(saved?.[key])?saved[key]:key==='permission'?defaultPermission(fields.provider.value):'default';}fields.network.value=saved?.network==null?'inherit':String(saved.network);fields.network.disabled=fields.provider.value!=='codex';}
 fields.provider.onchange=()=>agentOptions();fields.inheritAgent.onchange=()=>{$('background-agent-options').hidden=fields.inheritAgent.checked;};
 function fill(){if(!data)return;formCandidate=candidate;const task=data.task;fields.skillPath.value=task.skillPath??'';skillName();fields.enabled.checked=task.enabled;fields.intervalMinutes.value=task.intervalMinutes;fields.inheritAgent.checked=!task.agentOverride;fields.provider.replaceChildren(...getCatalog().filter(a=>a.supported&&['codex','claude','opencode'].includes(a.id)).map(a=>new Option(a.label,a.id)));fields.provider.value=task.agentSettings.provider;agentOptions(task.agentSettings);$('background-agent-options').hidden=fields.inheritAgent.checked;}
 function openSettings(show){form.hidden=!show;$('background-settings').setAttribute('aria-expanded',String(show));if(!show){$('background-skill-details').open=false;$('background-skill-content').textContent='';fill();}else fields.intervalMinutes.focus();}
 $('gmail-check').onclick=attempt(async()=>{const id=candidate;$('gmail-check').disabled=true;try{const access=await api.backgroundCheckGmail(id);if(candidate!==id)return;if(access.status==='available'&&!data?.runs.some(r=>r.status==='running'))await api.backgroundRun(id);await refresh();}finally{$('gmail-check').disabled=false;}});
 $('gmail-connect').onclick=attempt(async()=>{await api.backgroundConnectGmail(candidate);notice('Gmail bağlantısını tamamladıktan sonra Bağlantıyı kontrol et ve yeniden dene düğmesini kullan.');});
 $('background-settings').onclick=()=>openSettings(form.hidden);
 $('background-settings-cancel').onclick=()=>openSettings(false);
 $('background-pick-skill').onclick=attempt(async()=>{const id=candidate,file=await api.backgroundPickSkill();if(file&&candidate===id){fields.skillPath.value=file;skillName();}});
 $('background-default-skill').onclick=()=>{fields.skillPath.value='';skillName();};
 $('background-skill-details').ontoggle=attempt(async()=>{if(!$('background-skill-details').open)return;const id=candidate,content=await api.backgroundReadSkill(id);if(id===candidate)$('background-skill-content').textContent=content;});
 async function refresh(){const id=candidate;if(!id)return;const result=await api.backgroundSnapshot(id);if(id!==candidate)return;data=result;outcomes=data.mail?{...Object.fromEntries(data.mail.outcomes.map(o=>[o.id,o.label])),unmatched:'Eşleştirme gerekli'}:legacyOutcomes;form.inert=false;if(formCandidate!==id)fill();selectedRun=data.runs.find(r=>r.status==='running')?.id??data.runs[0]?.id??null;render();}
 function render(){if(!data)return;const now=Date.now(),task=data.task,active=data.runs.find(r=>r.status==='running'),last=data.runs.find(r=>r.status!=='running'),skill=skillLabel(task.skillPath);
 const blocked=!task.skillPath&&task.connection&&task.connection.status!=='ready',access=task.connectorAccess?.provider===task.agentSettings.provider?task.connectorAccess:null;
 $('gmail-access').hidden=Boolean(task.skillPath);$('gmail-connect').hidden=!access?.installUrl;$('gmail-access-message').textContent=access?.message??(blocked?'Gmail bağlantısı veya hesap doğrulaması gerekli. Otomatik tekrarlar bekletiliyor.':'Gmail agent’ın mevcut bağlantısını kullanır. Bağlantıyı kontrol edebilir veya mevcut MCP ile Şimdi çalıştır düğmesini kullanabilirsin.');
 $('background-status').dataset.tone=active?'running':task.enabled?'scheduled':'off';
 $('background-summary').textContent=active?'Çalışıyor':blocked?'Gmail bağlantısı gerekli':task.enabled?'Zamanlandı':'Kapalı';
 $('background-title').textContent=active?(phases[active.state]??active.state??'İşleniyor'):blocked?'Gmail bağlantısı bekleniyor':task.enabled?`Sonraki çalışma ${task.nextRunAt>now?relative(task.nextRunAt,{now}):'ilk uygun anda'}`:'Düzenli çalıştırma kapalı';
 $('background-detail').textContent=active?`${skill} ${relative(active.startedAt,{past:true,now})} başladı.`:task.enabled?`${skill} her ${task.intervalMinutes} dakikada bir çalıştırılır.`:`${skill} yalnızca elle başlatılır.`;
 const lastNode=$('background-last');lastNode.textContent=last?`Son çalışma ${relative(last.finishedAt??last.startedAt,{past:true,now})} ${verbs[last.status]??last.status}: ${last.summary}`:'Henüz çalıştırılmadı.';lastNode.title=last?time(last.finishedAt??last.startedAt):'';lastNode.toggleAttribute('data-alert',Boolean(last&&['failed','timeout','blocked','interrupted'].includes(last.status)));
 $('background-run').hidden=Boolean(active);$('background-run').disabled=Boolean(active);$('background-stop').hidden=!active;$('background-stop').disabled=!active;
 $('background-next').textContent=blocked?'Bağlantı doğrulanana kadar otomatik tekrar yapılmaz.':task.enabled?`Sonraki çalışma: ${active?'mevcut çalışma sonrası':task.nextRunAt>now?time(task.nextRunAt):'ilk uygun anda'}`:'Düzenli çalıştırma kapalı.';
 $('background-history').hidden=!data.runs.length;const runs=$('background-runs');runs.replaceChildren();for(const run of data.runs){const row=el('div',null,'run-row');row.dataset.status=run.status;const head=el('div',null,'run-head');head.append(el('b',states[run.status]??run.status),when(run.startedAt,{past:true,now}));row.append(head,el('span',run.summary,'run-summary'));runs.append(row);}
 $('background-chat-hint').textContent=active?(active.interactive?'Konuşma açık. Bitirmek için Durdur kullan.':'Mesaj gönderirsen bu oturum konuşma için açık kalır.'):'Görev kapalı. Mesajın yeni bir konuşma açar; son çalışmanın özeti aktarılır.';
 $('background-chat-send').textContent=active?'Gönder':'Konuşma aç ve gönder';
 const visible=data.signals.filter(s=>s.review!=='dismissed').sort((a,b)=>(b.review==='pending')-(a.review==='pending')||millis(b.date)-millis(a.date)),pending=visible.filter(s=>s.review==='pending').length,badge=$('background-badge');badge.hidden=!pending;badge.textContent=String(pending);badge.parentElement.title=pending?`${pending} mail eşleştirme bekliyor`:'Arka plan görevleri';
 $('background-signals-note').textContent=pending?`${pending} mail eşleştirme bekliyor`:visible.length?`${visible.length} mail`:'';
 const signals=$('background-signals'),focused=signals.contains(document.activeElement)&&document.activeElement.dataset.signalSearch?{id:document.activeElement.dataset.signalSearch,at:document.activeElement.selectionStart}:null;signals.className=visible.length?'signal-list':'';signals.replaceChildren();for(const signal of visible)signals.append(signalRow(signal,true));if(focused){const input=[...signals.querySelectorAll('[data-signal-search]')].find(node=>node.dataset.signalSearch===focused.id);if(input){input.focus();input.setSelectionRange(focused.at,focused.at);}}if(!visible.length)signals.append(el('p','Çalışma alanındaki kayıtlarla ilgili posta sonuçları burada görünecek.','background-empty'));renderJobSignals();
 }
 function signalRow(signal,review=false){const row=el('div',null,'mail-signal');row.dataset.outcome=signal.outcome;row.dataset.review=signal.review;const head=el('div',null,'mail-signal-head');const link=el('button','Maili aç ↗','mail-signal-link');link.type='button';link.onclick=attempt(()=>api.openLink(signal.url));head.append(el('b',outcomes[signal.outcome]??signal.outcome),el('span',signal.subject,'mail-signal-subject'),when(signal.date,{past:true}),link);row.append(head,el('p',signal.summary));
 if(review&&signal.review==='pending')row.append(signalReview(signal));
 return row;}
 // Matching a mail to one of many applications: search instead of a long select, with the mail's own words ranking suggestions.
 function signalReview(signal){const draft=drafts.get(signal.id)??{query:'',jobId:'',outcome:Object.hasOwn(outcomes,guessOutcome(signal))?guessOutcome(signal):''};drafts.set(signal.id,draft);const box=el('div',null,'signal-review');const apps=data.applications??[],text=fold([signal.subject,signal.summary,signal.evidence].filter(v=>typeof v==='string').join(' '));
  const scored=apps.map(job=>({job,score:matchScore(job,text)}));
  const picker=el('div',null,'app-picker'),outcome=el('select'),apply=el('button','Eşleştir','primary'),dismiss=el('button','Gözden geçirildi','quiet');
  outcome.setAttribute('aria-label','Kayıt sonucu');outcome.append(new Option('Sonucu seç',''),...Object.entries(outcomes).filter(([key])=>key!=='unmatched').map(([key,label])=>new Option(label,key)));outcome.value=draft.outcome;outcome.onchange=()=>{draft.outcome=outcome.value;};
  apply.type='button';dismiss.type='button';
  apply.onclick=attempt(async()=>{if(!draft.jobId||!outcome.value)throw Error(draft.jobId?'Sonucu seç':'Önce mailin ait olduğu kaydı seç');await api.resolveMailSignal(candidate,signal.id,draft.jobId,outcome.value);drafts.delete(signal.id);await refresh();});
  dismiss.onclick=attempt(async()=>{await api.dismissMailSignal(candidate,signal.id);drafts.delete(signal.id);await refresh();});
  function paint(){picker.replaceChildren();const chosen=apps.find(j=>j.id===draft.jobId);
   if(chosen){const chip=el('div',null,'app-picker-chosen');const change=el('button','Değiştir','quiet');change.type='button';change.onclick=()=>{draft.jobId='';paint();picker.querySelector('input')?.focus();};chip.append(appLabel(chosen),change);picker.append(chip);return;}
   const input=el('input');input.type='search';input.placeholder='Kayıt ara: kaynak veya başlık';input.value=draft.query;input.dataset.signalSearch=signal.id;input.setAttribute('aria-label','Mailin ilgili olduğu kaydı ara');const list=el('ul',null,'app-picker-list');list.id=`app-picker-${signal.id}`;list.setAttribute('role','listbox');input.setAttribute('role','combobox');input.setAttribute('aria-controls',list.id);input.setAttribute('aria-expanded','true');
   let active=0,shown=[];
   function choose(job){draft.jobId=job.id;draft.query='';paint();outcome.focus();}
   function fill(){const terms=fold(draft.query).split(' ').filter(Boolean);shown=terms.length?scored.filter(({job})=>{const hay=fold(`${job.company} ${job.role}`);return terms.every(t=>hay.includes(t));}).sort((a,b)=>b.score-a.score||a.job.company.localeCompare(b.job.company,'tr')):scored.filter(s=>s.score>0).sort((a,b)=>b.score-a.score).slice(0,5);active=Math.min(active,Math.max(shown.length-1,0));list.replaceChildren();
    const note=el('p',null,'app-picker-note');note.textContent=terms.length?(shown.length?`${shown.length} kayıt bulundu`:'Bu aramayla eşleşen kayıt yok'):(shown.length?'Mail içeriğiyle eşleşenler':`Mailden bir kayıt belirlenemedi. ${apps.length} kayıt arasında kaynak veya başlık yazarak ara.`);
    shown.slice(0,40).forEach(({job,score},index)=>{const option=el('li',null,'app-picker-option');option.id=`${list.id}-${index}`;option.setAttribute('role','option');option.setAttribute('aria-selected',String(index===active));option.append(appLabel(job));if(!terms.length&&index===0&&shown.length>1&&score>shown[1].score)option.dataset.best='true';option.onmousedown=event=>{event.preventDefault();choose(job);};option.onmousemove=()=>{if(active!==index){active=index;mark();}};list.append(option);});
    if(shown.length>40)list.append(el('li',`${shown.length-40} kayıt daha; aramayı daralt`,'app-picker-more'));
    picker.querySelector('.app-picker-note')?.remove();input.after(note);mark();}
   function mark(){[...list.querySelectorAll('[role=option]')].forEach((node,index)=>node.setAttribute('aria-selected',String(index===active)));const current=list.children[active];if(current?.id){input.setAttribute('aria-activedescendant',current.id);current.scrollIntoView({block:'nearest'});}else input.removeAttribute('aria-activedescendant');}
   input.oninput=()=>{draft.query=input.value;active=0;fill();};
   input.onkeydown=event=>{const count=Math.min(shown.length,40);if(event.key==='ArrowDown'&&count){event.preventDefault();active=(active+1)%count;mark();}else if(event.key==='ArrowUp'&&count){event.preventDefault();active=(active-1+count)%count;mark();}else if(event.key==='Enter'){event.preventDefault();if(shown[active])choose(shown[active].job);}else if(event.key==='Escape'&&input.value){event.preventDefault();input.value='';draft.query='';fill();}};
   picker.append(input,list);fill();}
  paint();const foot=el('div',null,'signal-review-foot');foot.append(outcome,apply,dismiss);box.append(picker,foot);return box;}
 function renderJobSignals(){for(const node of document.querySelectorAll('[data-job-mails]')){node.replaceChildren();const signals=(data?.signals??[]).filter(s=>s.jobId===node.dataset.jobMails&&s.review==='accepted').sort((a,b)=>Date.parse(b.date)-Date.parse(a.date));if(signals.length){const detail=el('details');detail.append(el('summary',`${outcomes[signals[0].outcome]} · ${signals.length} mail`));for(const signal of signals)detail.append(signalRow(signal));node.append(detail);}}}
 async function saveForm(){if(!candidate)return;if(!form.reportValidity())throw Error('Çalışma aralığını kontrol et');const id=candidate;await api.backgroundSave(id,{skillPath:fields.skillPath.value,enabled:fields.enabled.checked,intervalMinutes:Number(fields.intervalMinutes.value),agentOverride:fields.inheritAgent.checked?null:{provider:fields.provider.value,model:fields.model.value,permission:fields.permission.value,reasoning:fields.reasoning.value,network:fields.provider.value!=='codex'||fields.network.value==='inherit'?null:fields.network.value==='true'}});$('background-skill-details').open=false;$('background-skill-content').textContent='';return id;}
 form.onsubmit=attempt(async event=>{event.preventDefault();await saveForm();notice('Arka plan görevi kaydedildi.');await refresh();openSettings(false);});
 $('background-run').onclick=attempt(async()=>{$('background-run').disabled=true;try{const id=await saveForm();if(!id)return;await api.backgroundRun(id);if(candidate===id)await refresh();}finally{await refresh();}});
 $('background-chat-message').oninput=()=>{if(candidate)localStorage.setItem(`background-chat:${candidate}`,$('background-chat-message').value);};
 $('background-chat').onsubmit=attempt(async event=>{event.preventDefault();const id=candidate,text=$('background-chat-message').value;if(!id||!text.trim())return;$('background-chat-send').disabled=true;try{await api.backgroundMessage(id,text,selectedRun);localStorage.removeItem(`background-chat:${id}`);if(candidate===id){$('background-chat-message').value='';await refresh();$('background-chat-message').focus();}}finally{$('background-chat-send').disabled=false;}});
 $('background-stop').onclick=attempt(async()=>{await api.backgroundStop(candidate);await refresh();});
 api.onBackgroundChange(event=>{if(event.candidateId===candidate)refresh().catch(e=>notice(e.message));});
 return{select(id){if(id===candidate)return;candidate=id;drafts.clear();$('background-chat-message').value=id?localStorage.getItem(`background-chat:${id}`)??'':'';data=null;form.inert=true;formCandidate=null;selectedRun=null;form.hidden=true;$('background-settings').setAttribute('aria-expanded','false');$('background-skill-details').open=false;$('background-skill-content').textContent='';$('background-badge').hidden=true;if(id)refresh().catch(e=>notice(e.message));},renderJobSignals};
}
