import {XtermSurface} from '@termloop/terminal-surface/xterm';
import './background.css';
const outcomes={confirmation:'Başvuru alındı',interview:'Mülakat daveti',assessment:'Değerlendirme / test',offer:'Teklif',rejection:'Olumsuz dönüş',unmatched:'Eşleştirme gerekli'};
const states={running:'Çalışıyor',completed:'Tamamlandı',failed:'Hata',timeout:'Süre aşıldı',cancelled:'Durduruldu',interrupted:'Kesildi',blocked:'İşlem gerekiyor'};
const verbs={completed:'tamamlandı',failed:'hata verdi',timeout:'süre aşımına uğradı',cancelled:'durduruldu',interrupted:'kesildi',blocked:'işlem bekliyor'};
const phases={Starting:'Başlatılıyor',None:'Bağlantı / onay bekleniyor',Working:'İşleniyor',Idle:'Hazır',AwaitingInput:'Onay bekliyor',Compacting:'Özetleniyor'};
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e;};
const millis=value=>typeof value==='number'?value:Date.parse(value)||0;
const time=value=>millis(value)?new Date(millis(value)).toLocaleString('tr-TR'):'—';
function relative(value,{past=false,now=Date.now()}={}){const ms=millis(value);if(!ms)return '—';const minutes=Math.round(Math.abs(past?now-ms:ms-now)/60000);if(minutes<1)return past?'az önce':'şimdi';const unit=minutes<60?`${minutes} dk`:minutes<1440?`${Math.round(minutes/60)} sa`:`${Math.round(minutes/1440)} gün`;return `${unit} ${past?'önce':'sonra'}`;}
function when(value,options){const node=el('time',relative(value,options));node.title=time(value);return node;}
export function backgroundPage(api,{notice,getCatalog}){
 const host=document.getElementById('background');let candidate=null,data=null,selectedRun=null,latestActiveRun=null,terminal=null,terminalSize=null,sizeSent='',loadingTerminal=false,pendingOutput=[],generation=0,formCandidate=null;
 host.innerHTML=`<div class="background-head"><h2>Background Jobs</h2><p>Uygulama açıkken ayrı bir agent, seçtiğin skill’i belirlediğin aralıkla çalıştırır ve bitince kapanır. Gelen sonuçlar bu sayfada toplanır; model ve izinleri Ayarlar’dan seçebilirsin.</p></div>
<section id="background-status" class="background-status" data-tone="off" aria-label="Arka plan görevinin durumu"><div class="background-status-top"><div class="background-status-copy"><div class="background-status-label"><span id="background-summary"></span></div><h2 id="background-title"></h2><p id="background-detail"></p><small id="background-last"></small></div><div class="background-status-actions"><button id="background-run" class="quiet" type="button">Şimdi çalıştır</button><button id="background-stop" class="quiet" type="button">Durdur</button><button id="background-settings" class="quiet" type="button" aria-expanded="false" aria-controls="background-form">Ayarlar</button></div></div>
<div id="gmail-access" class="gmail-access"><p id="gmail-access-message"></p><div class="actions"><button id="gmail-check" type="button" class="quiet">Bağlantıyı kontrol et ve yeniden dene</button><button id="gmail-connect" type="button" class="primary" hidden>Gmail’i bağla ↗</button></div></div>
<form id="background-form" class="background-form" hidden><div class="background-skill"><span>Çalıştırılacak skill</span><input name="skillPath" type="hidden"><b id="background-skill-name">gmail-sync / SKILL.md</b><div class="background-skill-actions"><button id="background-pick-skill" type="button" class="quiet">Dosya seç</button><button id="background-default-skill" type="button" class="quiet">Gmail sync kullan</button></div><details id="background-skill-details"><summary>Skill içeriğini göster</summary><pre id="background-skill-content"></pre></details></div><div class="background-schedule"><label class="background-toggle"><input name="enabled" type="checkbox" class="switch"><span>Düzenli çalıştır<small>Uygulama açıkken belirlediğin aralıkla tekrarlar.</small></span></label><label>Çalışma aralığı (dakika)<input name="intervalMinutes" type="number" min="1" max="10080" required></label></div><div class="background-agent-settings"><label class="background-toggle"><input name="inheritAgent" type="checkbox" class="switch"><span>Adayın agent ayarlarını kullan</span></label><div id="background-agent-options" class="settings-grid"><label>Sağlayıcı<select name="provider"></select></label><label>Model<select name="model"></select></label><label>İzin modu<select name="permission"></select></label><label>Düşünme seviyesi<select name="reasoning"></select></label><label>Ağ erişimi<select name="network"><option value="inherit">Varsayılan</option><option value="true">İzin ver</option><option value="false">Kapat</option></select></label></div><small>Kaydedilen ayarlar bir sonraki oturumda uygulanır. Claude, kendi Gmail MCP bağlantısını kullanır.</small></div><div class="background-form-foot"><button class="primary" type="submit">Kaydet</button><button id="background-settings-cancel" class="quiet" type="button">Vazgeç</button><span id="background-next"></span></div></form></section>
<form id="background-chat" class="background-chat"><label for="background-chat-message">Görev agent’ına mesaj</label><textarea id="background-chat-message" maxlength="12000" required placeholder="Gmail görevi hakkında yaz…"></textarea><div class="actions"><button type="submit" class="primary" id="background-chat-send">Gönder</button><span id="background-chat-hint"></span></div></form>
<div class="section-title"><h2>Gelen sonuçlar</h2><span id="background-signals-note"></span></div><div id="background-signals"></div>
<section id="background-history" class="background-history" hidden><div class="section-title"><h2>Çalışma geçmişi</h2><span>Bir çalışmayı seçince çıktısı yanında açılır.</span></div><div class="background-history-grid"><div id="background-runs" class="run-list"></div><div class="background-terminal-frame"><div class="background-terminal-head"><span class="dot"></span><b id="background-output-label">Çalışma çıktısı</b><button id="background-write" class="quiet" type="button">Mesaj yaz</button><span id="background-terminal-title"></span></div><div id="background-terminal"></div></div></div></section>`;
 const $=id=>document.getElementById(id),form=$('background-form'),fields=form.elements;
 const attempt=fn=>async(...args)=>{try{await fn(...args);}catch(error){notice(error.message);}};
 const skillLabel=value=>value?value.split(/[\\/]/).slice(-2).join(' / '):'gmail-sync / SKILL.md';
 function skillName(){ $('background-skill-name').textContent=skillLabel(fields.skillPath.value);$('background-skill-name').title=fields.skillPath.value; }
 function agentOptions(saved){const current=getCatalog().find(a=>a.id===fields.provider.value);for(const [key,list]of [['model',current?.models??[]],['permission',current?.permissions??[]],['reasoning',current?.reasoning??[]]]){fields[key].replaceChildren(...list.map(value=>new Option(value,value)));fields[key].value=list.includes(saved?.[key])?saved[key]:'default';}fields.network.value=saved?.network==null?'inherit':String(saved.network);fields.network.disabled=fields.provider.value!=='codex';}
 fields.provider.onchange=()=>agentOptions();fields.inheritAgent.onchange=()=>{$('background-agent-options').hidden=fields.inheritAgent.checked;};
 function fill(){if(!data)return;formCandidate=candidate;const task=data.task;fields.skillPath.value=task.skillPath??'';skillName();fields.enabled.checked=task.enabled;fields.intervalMinutes.value=task.intervalMinutes;fields.inheritAgent.checked=!task.agentOverride;fields.provider.replaceChildren(...getCatalog().filter(a=>a.supported&&['codex','claude'].includes(a.id)).map(a=>new Option(a.label,a.id)));fields.provider.value=task.agentSettings.provider;agentOptions(task.agentSettings);$('background-agent-options').hidden=fields.inheritAgent.checked;}
 function openSettings(show){form.hidden=!show;$('background-settings').setAttribute('aria-expanded',String(show));if(!show){$('background-skill-details').open=false;$('background-skill-content').textContent='';fill();}else fields.intervalMinutes.focus();}
 $('gmail-check').onclick=attempt(async()=>{const id=candidate;$('gmail-check').disabled=true;try{const access=await api.backgroundCheckGmail(id);if(candidate!==id)return;if(access.status==='available'&&!data?.runs.some(r=>r.status==='running'))await api.backgroundRun(id);await refresh();}finally{$('gmail-check').disabled=false;}});
 $('gmail-connect').onclick=attempt(async()=>{await api.backgroundConnectGmail(candidate);notice('Gmail bağlantısını tamamladıktan sonra Bağlantıyı kontrol et ve yeniden dene düğmesini kullan.');});
 $('background-settings').onclick=()=>openSettings(form.hidden);
 $('background-settings-cancel').onclick=()=>openSettings(false);
 $('background-pick-skill').onclick=attempt(async()=>{const id=candidate,file=await api.backgroundPickSkill();if(file&&candidate===id){fields.skillPath.value=file;skillName();}});
 $('background-default-skill').onclick=()=>{fields.skillPath.value='';skillName();};
 $('background-skill-details').ontoggle=attempt(async()=>{if(!$('background-skill-details').open)return;const id=candidate,content=await api.backgroundReadSkill(id);if(id===candidate)$('background-skill-content').textContent=content;});
 async function refresh(){const id=candidate;if(!id)return;const result=await api.backgroundSnapshot(id);if(id!==candidate)return;data=result;form.inert=false;if(formCandidate!==id)fill();render();const active=data.runs.find(r=>r.status==='running');if(active&&latestActiveRun!==active.id){latestActiveRun=active.id;await selectRun(active.id);}else if(!selectedRun&&data.runs.length)await selectRun(data.runs[0].id);}
 // The worker PTY starts at a fixed size; push the visible grid so the agent redraws at the width we actually show.
 function syncSize(){const run=data?.runs.find(r=>r.id===selectedRun);if(!terminalSize||run?.status!=='running')return;const key=`${run.id}:${run.state}:${terminalSize.rows}x${terminalSize.cols}`;if(key===sizeSent)return;sizeSent=key;api.backgroundResize(candidate,run.id,terminalSize.rows,terminalSize.cols).catch(()=>{sizeSent='';});}
 async function selectRun(runId){selectedRun=runId;const id=candidate,version=++generation;loadingTerminal=true;pendingOutput=[];const bytes=await api.backgroundTerminal(id,runId);if(candidate!==id||version!==generation)return;if(!terminal){terminal=new XtermSurface(text=>{if(data?.runs.find(r=>r.id===selectedRun)?.status==='running')api.backgroundInput(candidate,selectedRun,text).catch(e=>notice(e.message));else{const input=$('background-chat-message');input.focus();if(text&&!/[\x00-\x1f\x7f]/.test(text)){input.setRangeText(text,input.selectionStart,input.selectionEnd,'end');input.dispatchEvent(new Event('input'));}}},(rows,cols)=>{terminalSize={rows,cols};syncSize();},()=>{});await terminal.mount($('background-terminal'),false);}terminal.write(new TextEncoder().encode('\x1b[2J\x1b[3J\x1b[H'),()=>{});terminal.write(new Uint8Array(bytes),()=>{});loadingTerminal=false;for(const chunk of pendingOutput)terminal.write(new Uint8Array(chunk),()=>{});syncSize();pendingOutput=[];render();}
 function render(){if(!data)return;syncSize();const now=Date.now(),task=data.task,active=data.runs.find(r=>r.status==='running'),last=data.runs.find(r=>r.status!=='running'),skill=skillLabel(task.skillPath);
 const blocked=!task.skillPath&&task.connection&&task.connection.status!=='ready',access=task.connectorAccess?.provider===task.agentSettings.provider?task.connectorAccess:null;
 $('gmail-access').hidden=Boolean(task.skillPath);$('gmail-connect').hidden=!access?.installUrl;$('gmail-access-message').textContent=access?.message??(blocked?'Gmail bağlantısı veya hesap doğrulaması gerekli. Otomatik tekrarlar bekletiliyor.':'Gmail agent’ın mevcut bağlantısını kullanır. Bağlantıyı kontrol edebilir veya mevcut MCP ile Şimdi çalıştır düğmesini kullanabilirsin.');
 $('background-status').dataset.tone=active?'running':task.enabled?'scheduled':'off';
 $('background-summary').textContent=active?'Çalışıyor':blocked?'Gmail bağlantısı gerekli':task.enabled?'Zamanlandı':'Kapalı';
 $('background-title').textContent=active?(phases[active.state]??active.state??'İşleniyor'):blocked?'Gmail bağlantısı bekleniyor':task.enabled?`Sonraki çalışma ${task.nextRunAt>now?relative(task.nextRunAt,{now}):'ilk uygun anda'}`:'Düzenli çalıştırma kapalı';
 $('background-detail').textContent=active?`${skill} ${relative(active.startedAt,{past:true,now})} başladı.`:task.enabled?`${skill} her ${task.intervalMinutes} dakikada bir çalıştırılır.`:`${skill} yalnızca elle başlatılır.`;
 const lastNode=$('background-last');lastNode.textContent=last?`Son çalışma ${relative(last.finishedAt??last.startedAt,{past:true,now})} ${verbs[last.status]??last.status}: ${last.summary}`:'Henüz çalıştırılmadı.';lastNode.title=last?time(last.finishedAt??last.startedAt):'';lastNode.toggleAttribute('data-alert',Boolean(last&&['failed','timeout','blocked','interrupted'].includes(last.status)));
 $('background-run').hidden=Boolean(active);$('background-run').disabled=Boolean(active);$('background-stop').hidden=!active;$('background-stop').disabled=!active;
 $('background-next').textContent=blocked?'Bağlantı doğrulanana kadar otomatik tekrar yapılmaz.':task.enabled?`Sonraki çalışma: ${active?'mevcut çalışma sonrası':task.nextRunAt>now?time(task.nextRunAt):'ilk uygun anda'}`:'Düzenli çalıştırma kapalı.';
 $('background-history').hidden=!data.runs.length;const runs=$('background-runs');runs.replaceChildren();for(const run of data.runs){const row=el('button',null,'run-row');row.type='button';row.dataset.status=run.status;row.classList.toggle('selected',run.id===selectedRun);row.setAttribute('aria-pressed',String(run.id===selectedRun));const head=el('div',null,'run-head');head.append(el('b',states[run.status]??run.status),when(run.startedAt,{past:true,now}));row.append(head,el('span',run.summary,'run-summary'));row.onclick=attempt(()=>selectRun(run.id));runs.append(row);}
 $('background-chat-hint').textContent=active?(active.interactive?'Konuşma açık. Bitirmek için Durdur kullan.':'Mesaj gönderirsen bu oturum konuşma için açık kalır.'):'Görev kapalı. Mesajın yeni bir konuşma açar; seçili çalışmanın özeti aktarılır.';
 const chat=$('background-chat'),destination=data.runs.length?host.querySelector('.background-terminal-frame'):host;if(chat.parentElement!==destination){if(data.runs.length)destination.append(chat);else host.insertBefore(chat,$('background-signals').previousElementSibling);}const run=data.runs.find(r=>r.id===selectedRun);$('background-output-label').textContent=run?.status==='running'?'Canlı agent terminali':'Kayıtlı çıktı · oturum kapalı';$('background-chat-send').textContent=active?'Gönder':'Konuşma aç ve gönder';$('background-terminal-title').textContent=run?run.status==='running'?(phases[run.state]??run.state):`${states[run.status]} · ${relative(run.finishedAt??run.startedAt,{past:true,now})}`:'Bir çalışma seç';
 const visible=data.signals.filter(s=>s.review!=='dismissed').sort((a,b)=>(b.review==='pending')-(a.review==='pending')||millis(b.date)-millis(a.date)),pending=visible.filter(s=>s.review==='pending').length,badge=$('background-badge');badge.hidden=!pending;badge.textContent=String(pending);badge.parentElement.title=pending?`${pending} mail eşleştirme bekliyor`:'Arka plan görevleri';
 $('background-signals-note').textContent=pending?`${pending} mail eşleştirme bekliyor`:visible.length?`${visible.length} mail`:'';
 const signals=$('background-signals');signals.className=visible.length?'signal-list':'';signals.replaceChildren();for(const signal of visible)signals.append(signalRow(signal,true));if(!visible.length)signals.append(el('p','Başvuru dönüşleri burada görünecek. Skill gelen kutunu tarar, başvurularınla ilgili mailleri buraya getirir.','background-empty'));renderJobSignals();
 }
 function signalRow(signal,review=false){const row=el('div',null,'mail-signal');row.dataset.outcome=signal.outcome;row.dataset.review=signal.review;const head=el('div',null,'mail-signal-head');const link=el('button','Maili aç ↗','mail-signal-link');link.type='button';link.onclick=attempt(()=>api.openLink(signal.url));head.append(el('b',outcomes[signal.outcome]??signal.outcome),el('span',signal.subject,'mail-signal-subject'),when(signal.date,{past:true}),link);row.append(head,el('p',signal.summary));
 if(review&&signal.review==='pending'){const match=el('select'),outcome=el('select');match.setAttribute('aria-label','Mailin ilgili olduğu başvuru');outcome.setAttribute('aria-label','Başvuru sonucu');match.append(new Option('Başvuruyu seç',''),...(data.applications??[]).map(j=>new Option(`${j.company} · ${j.role}`,j.id)));outcome.append(new Option('Sonucu seç',''),...Object.entries(outcomes).filter(([key])=>key!=='unmatched').map(([key,label])=>new Option(label,key)));const apply=el('button','Eşleştir','primary');apply.type='button';apply.onclick=attempt(async()=>{if(!match.value||!outcome.value)throw Error('Başvuruyu ve sonucu seç');await api.resolveMailSignal(candidate,signal.id,match.value,outcome.value);await refresh();});const dismiss=el('button','Gözden geçirildi','quiet');dismiss.type='button';dismiss.onclick=attempt(async()=>{await api.dismissMailSignal(candidate,signal.id);await refresh();});const actions=el('div',null,'mail-signal-actions');actions.append(match,outcome,apply,dismiss);row.append(actions);}
 return row;}
 function renderJobSignals(){for(const node of document.querySelectorAll('[data-job-mails]')){node.replaceChildren();const signals=(data?.signals??[]).filter(s=>s.jobId===node.dataset.jobMails&&s.review==='accepted').sort((a,b)=>Date.parse(b.date)-Date.parse(a.date));if(signals.length){const detail=el('details');detail.append(el('summary',`${outcomes[signals[0].outcome]} · ${signals.length} mail`));for(const signal of signals)detail.append(signalRow(signal));node.append(detail);}}}
 async function saveForm(){if(!candidate)return;if(!form.reportValidity())throw Error('Çalışma aralığını kontrol et');const id=candidate;await api.backgroundSave(id,{skillPath:fields.skillPath.value,enabled:fields.enabled.checked,intervalMinutes:Number(fields.intervalMinutes.value),agentOverride:fields.inheritAgent.checked?null:{provider:fields.provider.value,model:fields.model.value,permission:fields.permission.value,reasoning:fields.reasoning.value,network:fields.provider.value!=='codex'||fields.network.value==='inherit'?null:fields.network.value==='true'}});$('background-skill-details').open=false;$('background-skill-content').textContent='';return id;}
 form.onsubmit=attempt(async event=>{event.preventDefault();await saveForm();notice('Arka plan görevi kaydedildi.');await refresh();openSettings(false);});
 $('background-run').onclick=attempt(async()=>{$('background-run').disabled=true;try{const id=await saveForm();if(!id)return;const run=await api.backgroundRun(id);if(candidate===id){await refresh();await selectRun(run.id);}}finally{await refresh();}});
 $('background-write').onclick=()=>{$('background-chat-message').scrollIntoView({block:'nearest'});$('background-chat-message').focus();};
 $('background-chat-message').oninput=()=>{if(candidate)localStorage.setItem(`background-chat:${candidate}`,$('background-chat-message').value);};
 $('background-chat').onsubmit=attempt(async event=>{event.preventDefault();const id=candidate,text=$('background-chat-message').value;if(!id||!text.trim())return;$('background-chat-send').disabled=true;try{const run=await api.backgroundMessage(id,text,selectedRun);localStorage.removeItem(`background-chat:${id}`);if(candidate===id){$('background-chat-message').value='';await refresh();await selectRun(run.id);$('background-chat-message').focus();}}finally{$('background-chat-send').disabled=false;}});
 $('background-stop').onclick=attempt(async()=>{await api.backgroundStop(candidate);await refresh();});
 api.onBackgroundChange(event=>{if(event.candidateId===candidate)refresh().catch(e=>notice(e.message));});
 api.onBackgroundOutput(event=>{if(event.candidateId!==candidate||event.runId!==selectedRun)return;if(loadingTerminal)pendingOutput.push(event.bytes);else terminal?.write(new Uint8Array(event.bytes),()=>{});});
 return{select(id){if(id===candidate)return;candidate=id;$('background-chat-message').value=id?localStorage.getItem(`background-chat:${id}`)??'':'';data=null;form.inert=true;formCandidate=null;selectedRun=null;latestActiveRun=null;generation++;form.hidden=true;$('background-settings').setAttribute('aria-expanded','false');$('background-skill-details').open=false;$('background-skill-content').textContent='';$('background-badge').hidden=true;terminal?.write(new TextEncoder().encode('\x1b[2J\x1b[3J\x1b[H'),()=>{});if(id)refresh().catch(e=>notice(e.message));},renderJobSignals};
}
