import './config.css';
const node=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
const size=text=>text.length>=1000?`${(text.length/1000).toFixed(1).replace('.0','')}k karakter`:`${text.length} karakter`;
// Text with {{placeholders}} rendered as marks, never as HTML.
function richText(text){const pre=node('pre');const parts=text.split(/(\{\{[^}]+\}\})/);for(const part of parts){if(/^\{\{[^}]+\}\}$/.test(part))pre.append(node('mark','',part.slice(2,-2)));else if(part)pre.append(document.createTextNode(part));}return pre;}
function body(text){const wrap=node('div','prompt-body');const copy=node('button','quiet copy','Kopyala');copy.type='button';copy.onclick=async()=>{try{await navigator.clipboard.writeText(text);copy.dataset.done='';copy.textContent='Kopyalandı';setTimeout(()=>{delete copy.dataset.done;copy.textContent='Kopyala';},1500);}catch{}};const head=node('div','prompt-body-head');head.append(copy);wrap.append(head,richText(text));return wrap;}
function card({title,when,path,text,open=false}){const details=node('details','prompt-card');details.open=open;details.dataset.search=(title+' '+(when??'')+' '+text).toLowerCase();const summary=node('summary');const main=node('span');main.append(node('span','prompt-title',title));if(when)main.append(node('span','prompt-when',when));if(path)main.append(node('code','prompt-path',path));summary.append(main,node('span','prompt-size',size(text)));details.append(summary,body(text));return details;}
// Phone access panel (desktop only). QR codes come as SVG markup generated by the main process from our own URL.
function phonePanel(api,{notice}){
 const box=document.getElementById('phone-access'),badge=()=>document.querySelector('.config-nav a[href="#config-phone"] b');let status=null,selected=0,busy=false;
 async function load(){try{status=await api.mobileStatus();render();}catch(e){notice(e.message);}}
 const act=fn=>async()=>{if(busy)return;busy=true;render();try{status=await fn();}catch(e){notice(e.message);}finally{busy=false;render();}};
 function render(){
  if(!status){box.replaceChildren();return;}
  badge().textContent=status.running?(status.devices?`${status.devices} bağlı`:'Açık'):'';
  const card=node('div','phone-card');card.dataset.state=status.running?'on':'off';
  const head=node('div','phone-head'),state=node('div','phone-state');state.append(node('b','',status.running?'Telefondan erişim açık':'Telefondan erişim kapalı'),node('span','',status.running?(status.devices?`${status.devices} cihaz şu an bağlı`:'Henüz bağlı cihaz yok'):'Açtığında bu Mac yerel ağda bir bağlantı noktası açar.'));
  const toggle=node('button',status.running?'quiet':'primary',status.running?'Kapat':'Telefondan erişimi aç');toggle.type='button';toggle.disabled=busy;toggle.onclick=act(()=>api.mobileEnable(!status.running));head.append(state,toggle);card.append(head);
  if(status.error)card.append(node('p','phone-error',`Başlatılamadı: ${status.error}`));
  if(status.running&&!status.urls.length)card.append(node('p','phone-error','Bu Mac şu an bir ağa bağlı değil. Wi‑Fi’a bağlanınca adres burada görünür.'));
  if(status.running&&status.urls.length){
   selected=Math.min(selected,status.urls.length-1);const current=status.urls[selected];
   const body=node('div','phone-body'),qr=node('div','phone-qr');qr.innerHTML=current.qr;qr.setAttribute('role','img');qr.setAttribute('aria-label','Telefonla taranacak QR kod');
   const side=node('div','phone-side'),steps=node('ol','phone-steps');for(const step of ['Telefonun kamerasıyla QR kodu tara.','Açılan sayfada Paylaş → Ana Ekrana Ekle’ye dokun.','Bundan sonra JobLoop’u simgesinden aç.'])steps.append(node('li','',step));
   side.append(steps);
   if(status.urls.length>1){const choices=node('div','phone-choices');status.urls.forEach((u,i)=>{const b=node('button',i===selected?'selected':'',`${u.label} · ${u.address}`);b.type='button';b.setAttribute('aria-pressed',String(i===selected));b.onclick=()=>{selected=i;render();};choices.append(b);});side.append(choices);}
   const address=node('div','phone-address'),code=node('code','',current.url),copy=node('button','quiet','Bağlantıyı kopyala');copy.type='button';copy.onclick=async()=>{try{await navigator.clipboard.writeText(current.pairUrl);copy.textContent='Kopyalandı';setTimeout(()=>{copy.textContent='Bağlantıyı kopyala';},1500);}catch{}};address.append(code,copy);side.append(address);
   body.append(qr,side);card.append(body);
   const foot=node('div','phone-foot'),warn=node('p','',`Bağlantı yerel ağda şifrelenmeden gider. Kafe veya ofis gibi ortak ağlarda açık bırakma. Evden uzaktayken bağlanmak için iki cihaza da Tailscale kur; adresi bu listede görünür.`),rotate=node('button','quiet phone-rotate','Bağlantıyı sıfırla');rotate.type='button';rotate.disabled=busy;rotate.title='Bağlı telefonların hepsi çıkış yapar';rotate.onclick=()=>{if(confirm('Bağlı telefonların hepsi çıkış yapar ve QR kodu yeniden taramaları gerekir. Devam edilsin mi?'))act(()=>api.mobileRotate())();};foot.append(warn,rotate);card.append(foot);
  }
  box.replaceChildren(card);
 }
 return {load,visible:()=>!box.closest('#config').hidden};
}
export function configPage(api,{notice,relativeTime}){
 const root=document.getElementById('config');
 root.innerHTML=`<div class="config-head"><div><h2>Yapılandırma</h2><p>Telefon bağlantısı ve agent’a giden her metin: çalışma alanı talimatları, görev promptları, beceriler ve MCP araçları.</p></div><label class="config-search"><input id="config-search" type="search" placeholder="Metinlerde ara" aria-label="Metinlerde ara"><small id="config-search-note"></small></label></div>
<div class="config-body"><nav class="config-nav" aria-label="Bölümler"><a href="#config-phone">Telefon<b></b></a><a href="#config-instructions">Talimatlar<b></b></a><a href="#config-tasks">Görev promptları<b></b></a><a href="#config-skills">Beceriler<b></b></a><a href="#config-tools">MCP araçları<b></b></a></nav>
<div class="config-sections">
<section id="config-phone" class="config-section phone-access"><h3>Telefon</h3><p>JobLoop’u telefonundan kullan: başvuruları izle, agent’ın sorularını yanıtla, agent’ı başlat ya da durdur. Veriler bu Mac’te kalır; telefon yalnızca bağlanır, bu yüzden JobLoop burada açık olmalı.</p><div id="phone-access"></div></section>
<section id="config-instructions" class="config-section"><h3>Talimatlar</h3><p>Her oturumda agent’ın önüne konan sabit metinler.</p><div id="config-instructions-list"></div></section>
<section id="config-tasks" class="config-section"><h3>Görev promptları</h3><p>Kampanya her görevi bu şablonlardan biriyle gönderir. Mavi alanlar o anda gerçek değerle dolar.</p><div id="config-tasks-list"></div></section>
<section id="config-skills" class="config-section"><h3>Beceriler</h3><p>Aday çalışma alanına kopyalanan SKILL.md dosyaları. Agent çalışmaya başlamadan bunları okur.</p><div id="config-skills-list"></div></section>
<section id="config-tools" class="config-section"><h3>MCP araçları</h3><p>Agent’ın profil ve başvuru verisine ulaştığı araçlar ve parametreleri. Tarayıcı araçları ayarlara göre ayrıca eklenir. Çerçeveli parametreler zorunlu.</p><div id="config-tools-list" class="tool-list"></div></section>
</div></div>`;
 const $=id=>root.querySelector('#'+id);
 let catalog=null,candidate=null,dirty=true,loading=false;
 const lists={instructions:$('config-instructions-list'),tasks:$('config-tasks-list'),skills:$('config-skills-list'),tools:$('config-tools-list')};
 for(const a of root.querySelectorAll('.config-nav a'))a.onclick=e=>{e.preventDefault();$(a.getAttribute('href').slice(1)).scrollIntoView({behavior:'smooth',block:'start'});};
 const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){for(const a of root.querySelectorAll('.config-nav a'))a.classList.toggle('active',a.getAttribute('href')==='#'+entry.target.id);}},{rootMargin:'-20% 0px -70% 0px'});
 for(const section of root.querySelectorAll('.config-section'))observer.observe(section);
 function counts(){const query=$('config-search').value.trim().toLowerCase();let shown=0,total=0;for(const [key,list]of Object.entries(lists)){const items=[...list.querySelectorAll('[data-search]')];let visible=0;for(const item of items){const hit=!query||item.dataset.search.includes(query);item.hidden=!hit;if(hit)visible++;}shown+=visible;total+=items.length;const badge=root.querySelector(`.config-nav a[href="#config-${key}"] b`);badge.textContent=query?`${visible}/${items.length}`:String(items.length);list.querySelector('.config-nomatch')?.remove();if(query&&items.length&&!visible){list.append(node('p','config-empty config-nomatch','Bu bölümde eşleşme yok.'));}}$('config-search-note').textContent=query?`${shown} / ${total} eşleşme`:'';}
 $('config-search').oninput=counts;
 function renderCatalog(){
  lists.instructions.replaceChildren(...catalog.instructions.map(p=>card({title:p.title,when:`${p.where} · ${p.when}`,text:p.text,open:p.id==='agents-md'})));
  lists.tasks.replaceChildren(...catalog.tasks.map(p=>card({title:p.title,when:p.when,text:p.text,open:p.id==='search-source'})));
  lists.skills.replaceChildren(...catalog.skills.map(s=>card({title:s.title,when:`${s.usedBy} · ${s.description}`,path:s.path,text:s.text})));
  lists.tools.replaceChildren(...catalog.tools.map(t=>{const el=node('div','tool-card');el.dataset.search=(t.name+' '+t.description+' '+t.params.map(p=>p.name).join(' ')).toLowerCase();el.append(node('code','',t.name),node('p','',t.description));const params=node('div','tool-params');for(const p of t.params){const chip=node('span');chip.dataset.required=String(p.required);chip.append(p.name,node('i','',': '+p.type));params.append(chip);}if(t.params.length)el.append(params);return el;}));
 }
 const phone=api.mobileStatus?phonePanel(api,{notice}):null;
 if(phone)setInterval(()=>{if(phone.visible())phone.load();},5000);
 async function load(){if(root.hidden||loading)return;loading=true;phone?.load();try{if(!catalog){catalog=await api.promptCatalog();renderCatalog();}dirty=false;counts();}catch(e){notice(e.message);}finally{loading=false;}}
 return {select(id){if(id!==candidate){candidate=id;dirty=true;}load();},refresh(){dirty=true;load();},show(){if(dirty||!catalog)load();}};
}
