export function updatesPanel(api,root,{notice=()=>{}}={}){
 root.classList.add('jev-settings');
 root.innerHTML=`<h3>Uygulama güncellemeleri</h3><p data-version></p><p data-status role="status"></p><div class="jev-settings-actions"><button type="button" data-check>Güncellemeleri kontrol et</button><button type="button" data-download hidden>İndir</button><button type="button" data-install hidden>Yedekle ve yeniden başlat</button><button type="button" class="quiet" data-releases>Sürümler sayfasını aç</button></div><p>Güncelleme kurulmadan önce çalışan görevleri durdur. Verilerin otomatik yedeği alınır; ardından AutoJev yeniden başlar. Kontrol ve indirme yalnızca bu düğmelerle başlatılır.</p>`;
 const $=selector=>root.querySelector(selector);let state=null,busy=false;
 const messages={idle:'Güncellemeleri buradan kontrol edebilirsin.',checking:'Yeni sürüm kontrol ediliyor…',available:'Yeni sürüm indirilmeye hazır.',current:'En güncel sürümü kullanıyorsun.',downloading:'Güncelleme indiriliyor…',downloaded:'İndirme tamamlandı. Kurmak için görevleri durdur.',installing:'Yedek alındı. Güncelleme kuruluyor…',unsupported:'Bu kurulumda uygulama içinden güncelleme desteklenmiyor. Sürümler sayfasından uygun paketi indir.',error:'Güncelleme tamamlanamadı.'};
 function render(){if(!state)return;$('[data-version]').textContent=`Yüklü sürüm: ${state.version}${state.availableVersion?' · Yeni sürüm: '+state.availableVersion:''}`;$('[data-status]').textContent=state.error||messages[state.status]||state.status;if(state.status==='downloading')$('[data-status]').textContent+=` %${Math.round(state.progress??0)}`;for(const button of root.querySelectorAll('button'))button.disabled=busy||['checking','downloading','installing'].includes(state.status);$('[data-check]').hidden=!state.enabled;$('[data-download]').hidden=state.status!=='available';$('[data-install]').hidden=state.status!=='downloaded';}
 async function action(fn){if(busy)return;busy=true;render();try{state=await fn();}catch(error){notice(error.message);}finally{busy=false;render();}}
 $('[data-check]').onclick=()=>action(()=>api.updateCheck());$('[data-download]').onclick=()=>action(()=>api.updateDownload());$('[data-install]').onclick=()=>action(()=>api.updateInstall());$('[data-releases]').onclick=()=>api.openLink('https://github.com/feritzcan2/AutoJev/releases').catch(error=>notice(error.message));
 api.onUpdateStatus?.(next=>{state=next;render();});
 return {async load(){try{state=await api.updateStatus();render();}catch(error){notice(error.message);}}};
}
