import {applicationMailContract} from '../mail-contract.mjs';
import {jobSearchSources} from './job-search-sources.mjs';
// Domain instructions and fields only. Execution, sources and UI use the same
// browser automation contract as every other template.
export const jobSearchTemplate={
 mail:applicationMailContract,
 defaultSources:jobSearchSources,
 id:'job-search',version:2,kind:'web',title:'İş arama',icon:'↗',description:'Uygun ilanları bul, değerlendir, başvuruları hazırla ve sonuçlarını takip et.',defaultMode:'observe',
 records:{identity:'url',dismissLabel:'Başvuruyu ele'},
 recordOperations:{score:{label:'Puanla'},prepare:{label:'Başvuruyu hazırla',instructions:'Read the full vacancy, candidate CV and saved application rules. Inspect the actual application form. Prepare exact answers and document paths, explaining eligibility and any missing facts through record-scoped questions. Save the complete application as a proposal. Do not submit an application during preparation.'},execute:{label:'Başvur',runningLabel:'Başvuruluyor',reviewLabel:'Onayla ve başvur',successCriteria:'The employer or portal shows confirmation for this exact vacancy and candidate, or its application history lists this application. Save the observed confirmation; an Apply button click is insufficient.'}},
 fields:[
  {id:'preferences',label:'İş tercihleri',question:'Hangi roller, ülkeler ve çalışma şekilleri uygun?',required:true,type:'text'},
  {id:'experience',label:'Deneyim ve yetkinlikler',question:'CV ve belgelerine göre hangi deneyim ve yetkinliklerin var?',required:false,type:'text'},
  {id:'constraints',label:'Kesin şartlar',question:'Maaş, çalışma izni, dil ve başlangıç tarihi şartların neler?',required:false,type:'text'},
  {id:'ranking',label:'Puanlama kriterleri',question:'Hangi kriterlere göre puanlayalım? Yetkinlik, deneyim, rol ve çalışma tercihlerinin ağırlıkları, kesin şartların ve başvuru için alt puan sınırın neler?',required:true,type:'text'},
  {id:'application_policy',label:'Başvuru kuralları',question:'Başvurularda hangi şartlara ve onay tercihlerine uyulmalı?',required:false,type:'text'}
 ],
 table:{title:'Başvuru akışı',columns:[{key:'source',label:'Kaynak',type:'text'},{key:'title',label:'Pozisyon',type:'text'},{key:'company',label:'Şirket',type:'text'},{key:'location',label:'Konum',type:'text'},{key:'score',label:'Uygunluk puanı',type:'number'}]},
 steps:['Profili ve CV belgelerini incele','Güncel ilanları bul ve uygunluğunu değerlendir','Başvuru belgelerini ve cevaplarını hazırla','Yetki kapsamında başvur ve sonucu doğrula'],
 guidance:`During initial setup, agree on scoring criteria with the user and save them in criteria.ranking before setup review. Read the CV and preferences, propose concrete criteria and weights totaling 100%, explain the 0–100 scale and ask about hard constraints and any application threshold. Recommendations are drafts until the user confirms or reviews them; do not assume missing qualifications or permissions. When the user asks to define or change scoring criteria later, use the same conversation and save_automation_plan to propose updated criteria.ranking, preserving their other profile fields and sources. Explain that saving the reviewed profile applies it to future assessments; existing records require manual rescoring. Both discovery and manual scoring use this same saved rubric. Explain the weighted calculation in the assessment summary, including how unknown information affects the result.
Before saving each new production listing, the discovering agent must read its full detail, evaluate it and include assessment in record_automation_result. Include status, score, summary, evidenceUrl, evidence, strengths, gaps and uncertainties. Do not save an unassessed listing and defer scoring to another worker. If details are inaccessible, save status=unavailable and score=null with the observed reason. Research/trial samples are exempt and must not receive suitability scores. Existing records can be rescored through the separate Puanla operation. If an older workspace has no saved rubric, ask the user to define criteria.ranking before evaluating; never silently choose a new rubric.
Use the saved preferences and workspace documents, including the CV, to find current job listings. Record exact listing URLs, company, role, location, verified requirements and an explained fit score in the table. Follow criteria.ranking and criteria.application_policy, including score thresholds and consent decisions; missing or below-threshold scores cannot qualify for automatic applications. Current saved criteria take precedence over archived referenceData; use archived facts only when not corrected by the user. Do not invent experience, qualifications, language skills, immigration status, salary, consent or personal facts. Read application forms and required documents before preparing a complete individual proposal. Ask the user through workspace questions when a necessary fact or document is missing. Save prepared documents under documents/ and link them to the record. Respect the source and workspace permission and saved application policies. Check existing records and submission evidence before acting, including records imported from earlier versions. Never repeat a completed or uncertain submission. Verify an uncertain result without resubmitting. Record the attempt before submitting and save fresh confirmation evidence afterwards. Treat inaccessible or expired listings honestly. Resume saved scan progress; do not skip remaining result pages. Save in-scope low-fit and uncertain findings with their explained scores so later scans can reuse them; score thresholds control qualification, not whether a finding is recorded.
Source discovery: ATS vendor homepages are not central job boards. For Greenhouse look for employer boards on boards.greenhouse.io and job-boards.greenhouse.io; for Lever jobs.lever.co; for Ashby jobs.ashbyhq.com; for Personio employer subdomains under jobs.personio.de and jobs.personio.com. These hostnames are discovery hints, not evidence that a particular listing is live. For JOIN use observed public company vacancy links under join.com/companies; an authenticated talent dashboard is not proof that public vacancies require login. Use managed-browser web searches constrained to the relevant host and the saved role/location preferences, plus existing result URLs as seeds. Follow actual observed employer boards and inspect current vacancies. Do not require MyGreenhouse or an employer account merely because the vendor homepage links to one. A redirecting vendor root is neither a completed job search nor a reason to remove the source. For every saved role/location query, continue its result pages and relevant details; keep each query and its remaining work in save_scan_searches/get_scan_queue, and document the actual search coverage without claiming to enumerate every employer on the web.`,
};
