import {applicationMailContract} from '../mail-contract.mjs';
import {jobSearchSources} from './job-search-sources.mjs';
// Domain instructions and fields only. Execution, sources and UI use the same
// browser automation contract as every other template.
export const jobSearchTemplate={
 mail:applicationMailContract,
 defaultSources:jobSearchSources,
 id:'job-search',version:2,kind:'web',title:'İş arama',icon:'↗',description:'Uygun ilanları bul, değerlendir, başvuruları hazırla ve sonuçlarını takip et.',defaultMode:'observe',
 records:{identity:'url',dismissLabel:'Başvuruyu ele'},
 recordOperations:{score:{label:'Puanla'},prepare:{label:'Başvuruyu hazırla',instructions:'Read the full vacancy, candidate CV and saved application rules. Inspect the actual application form. Prepare exact answers and document paths, explaining eligibility and any missing facts through record-scoped questions. Save the complete application as a proposal. Do not submit an application during preparation.'},execute:{label:'Başvur',runningLabel:'Başvuruluyor',reviewLabel:'Onayla ve başvur',successCriteria:'The employer or portal shows confirmation for this exact vacancy and candidate, or its application history lists this application. Save the observed confirmation; an Apply button click is insufficient.'}},
 fields:[
  {id:'preferences',label:'İş tercihleri',question:'Hangi roller, ülkeler ve çalışma şekilleri uygun?',required:true,type:'text'},
  {id:'experience',label:'Deneyim ve yetkinlikler',question:'CV ve belgelerine göre hangi deneyim ve yetkinliklerin var?',required:false,type:'text'},
  {id:'constraints',label:'Kesin şartlar',question:'Maaş, çalışma izni, dil ve başlangıç tarihi şartların neler?',required:false,type:'text'},
  {id:'ranking',label:'Puanlama kriterleri',question:'Hangi kriterlere göre puanlayalım? Yetkinlik, deneyim, rol ve çalışma tercihlerinin ağırlıkları, kesin şartların ve başvuru için alt puan sınırın neler?',required:true,type:'text'},
  {id:'application_policy',label:'Başvuru kuralları',question:'Başvurularda hangi şartlara ve onay tercihlerine uyulmalı?',required:false,type:'text'}
 ],
 table:{title:'Başvuru akışı',columns:[{key:'source',label:'Kaynak',type:'text'},{key:'title',label:'Pozisyon',type:'text'},{key:'company',label:'Şirket',type:'text'},{key:'location',label:'Konum',type:'text'},{key:'score',label:'Uygunluk puanı',type:'number'}]},
 steps:['Profili ve CV belgelerini incele','Güncel ilanları bul ve uygunluğunu değerlendir','Başvuru belgelerini ve cevaplarını hazırla','Yetki kapsamında başvur ve sonucu doğrula'],
 guidance:`Setup: agree on scoring criteria with the user and save them in criteria.ranking before setup review. Read the CV and preferences, propose concrete criteria and weights totaling 100%, explain the 0–100 scale, and ask about hard constraints and an application threshold. Recommendations stay drafts until the user confirms. When the user later asks to change criteria, propose updated criteria.ranking through save_automation_plan while preserving the other fields; saving the reviewed profile applies it to future assessments and existing records need manual rescoring.
Scoring: before saving each new production listing, read its detail (with Jev: read_jev_brief first) and send score (integer 0–100 following criteria.ranking and scoringPolicy.instructions) and optional scoreReason in record_automation_result. Preserve mandatory skills; distinguish possible home office from confirmed full remote, and site salary estimates from employer offers. If details are inaccessible, save score=null with the reason. Research and trial samples get no score. Never save an unassessed listing for another worker to score. If the workspace has no saved rubric, ask the user to define criteria.ranking first.
Search and records: use the saved preferences and documents, including the CV, to find current listings. Record exact listing URLs, company, role, location, verified requirements and the explained score. Follow criteria.ranking and criteria.application_policy, including thresholds and consent decisions; below-threshold or missing scores never qualify for automatic applications. Current saved criteria take precedence over archived referenceData. Never invent experience, qualifications, language skills, immigration status, salary, consent or personal facts. Read the application form and required documents before preparing a complete proposal; ask the user through workspace questions when a fact or document is missing. Save prepared documents under documents/ and link them to the record. Check existing records and submission evidence before acting; never repeat a completed or uncertain submission, and verify an uncertain result without resubmitting. Record the attempt before submitting and save fresh confirmation afterwards. Report inaccessible or expired listings honestly. Resume saved scan progress and do not skip result pages. Save in-scope low-fit and uncertain findings with their scores; thresholds control qualification, not whether a finding is recorded.
Source discovery: applicant-tracking vendor homepages are not job boards; the actual listings live on employer boards hosted by the vendor. Use managed-browser web searches limited to the relevant host plus the saved role and location preferences, and existing result URLs as seeds. Follow observed employer boards and inspect current vacancies. A redirecting vendor root is neither a completed search nor a reason to remove the source. Keep each query and its remaining work in save_scan_searches/get_scan_queue and document the actual coverage.`,
};
